
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.2.0
 * Query Engine version: 0c8ef2ce45c83248ab3df073180d5eda9e8be7a3
 */
export const prismaVersion: PrismaVersion = {
  client: "7.2.0",
  engine: "0c8ef2ce45c83248ab3df073180d5eda9e8be7a3"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Participant: 'Participant',
  EmergencyContact: 'EmergencyContact',
  Staff: 'Staff',
  Incident: 'Incident',
  ShiftReport: 'ShiftReport',
  RestrictivePractice: 'RestrictivePractice',
  Risk: 'Risk',
  RegulatoryItem: 'RegulatoryItem'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "participant" | "emergencyContact" | "staff" | "incident" | "shiftReport" | "restrictivePractice" | "risk" | "regulatoryItem"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Participant: {
      payload: Prisma.$ParticipantPayload<ExtArgs>
      fields: Prisma.ParticipantFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ParticipantFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ParticipantFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>
        }
        findFirst: {
          args: Prisma.ParticipantFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ParticipantFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>
        }
        findMany: {
          args: Prisma.ParticipantFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>[]
        }
        create: {
          args: Prisma.ParticipantCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>
        }
        createMany: {
          args: Prisma.ParticipantCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ParticipantCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>[]
        }
        delete: {
          args: Prisma.ParticipantDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>
        }
        update: {
          args: Prisma.ParticipantUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>
        }
        deleteMany: {
          args: Prisma.ParticipantDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ParticipantUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ParticipantUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>[]
        }
        upsert: {
          args: Prisma.ParticipantUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ParticipantPayload>
        }
        aggregate: {
          args: Prisma.ParticipantAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateParticipant>
        }
        groupBy: {
          args: Prisma.ParticipantGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ParticipantGroupByOutputType>[]
        }
        count: {
          args: Prisma.ParticipantCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ParticipantCountAggregateOutputType> | number
        }
      }
    }
    EmergencyContact: {
      payload: Prisma.$EmergencyContactPayload<ExtArgs>
      fields: Prisma.EmergencyContactFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EmergencyContactFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EmergencyContactFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>
        }
        findFirst: {
          args: Prisma.EmergencyContactFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EmergencyContactFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>
        }
        findMany: {
          args: Prisma.EmergencyContactFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>[]
        }
        create: {
          args: Prisma.EmergencyContactCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>
        }
        createMany: {
          args: Prisma.EmergencyContactCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EmergencyContactCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>[]
        }
        delete: {
          args: Prisma.EmergencyContactDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>
        }
        update: {
          args: Prisma.EmergencyContactUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>
        }
        deleteMany: {
          args: Prisma.EmergencyContactDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EmergencyContactUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EmergencyContactUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>[]
        }
        upsert: {
          args: Prisma.EmergencyContactUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EmergencyContactPayload>
        }
        aggregate: {
          args: Prisma.EmergencyContactAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEmergencyContact>
        }
        groupBy: {
          args: Prisma.EmergencyContactGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmergencyContactGroupByOutputType>[]
        }
        count: {
          args: Prisma.EmergencyContactCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EmergencyContactCountAggregateOutputType> | number
        }
      }
    }
    Staff: {
      payload: Prisma.$StaffPayload<ExtArgs>
      fields: Prisma.StaffFieldRefs
      operations: {
        findUnique: {
          args: Prisma.StaffFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.StaffFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>
        }
        findFirst: {
          args: Prisma.StaffFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.StaffFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>
        }
        findMany: {
          args: Prisma.StaffFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>[]
        }
        create: {
          args: Prisma.StaffCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>
        }
        createMany: {
          args: Prisma.StaffCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.StaffCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>[]
        }
        delete: {
          args: Prisma.StaffDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>
        }
        update: {
          args: Prisma.StaffUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>
        }
        deleteMany: {
          args: Prisma.StaffDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.StaffUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.StaffUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>[]
        }
        upsert: {
          args: Prisma.StaffUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$StaffPayload>
        }
        aggregate: {
          args: Prisma.StaffAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateStaff>
        }
        groupBy: {
          args: Prisma.StaffGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StaffGroupByOutputType>[]
        }
        count: {
          args: Prisma.StaffCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.StaffCountAggregateOutputType> | number
        }
      }
    }
    Incident: {
      payload: Prisma.$IncidentPayload<ExtArgs>
      fields: Prisma.IncidentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IncidentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IncidentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>
        }
        findFirst: {
          args: Prisma.IncidentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IncidentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>
        }
        findMany: {
          args: Prisma.IncidentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>[]
        }
        create: {
          args: Prisma.IncidentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>
        }
        createMany: {
          args: Prisma.IncidentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IncidentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>[]
        }
        delete: {
          args: Prisma.IncidentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>
        }
        update: {
          args: Prisma.IncidentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>
        }
        deleteMany: {
          args: Prisma.IncidentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IncidentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IncidentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>[]
        }
        upsert: {
          args: Prisma.IncidentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IncidentPayload>
        }
        aggregate: {
          args: Prisma.IncidentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIncident>
        }
        groupBy: {
          args: Prisma.IncidentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IncidentGroupByOutputType>[]
        }
        count: {
          args: Prisma.IncidentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IncidentCountAggregateOutputType> | number
        }
      }
    }
    ShiftReport: {
      payload: Prisma.$ShiftReportPayload<ExtArgs>
      fields: Prisma.ShiftReportFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ShiftReportFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ShiftReportFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>
        }
        findFirst: {
          args: Prisma.ShiftReportFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ShiftReportFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>
        }
        findMany: {
          args: Prisma.ShiftReportFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>[]
        }
        create: {
          args: Prisma.ShiftReportCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>
        }
        createMany: {
          args: Prisma.ShiftReportCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ShiftReportCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>[]
        }
        delete: {
          args: Prisma.ShiftReportDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>
        }
        update: {
          args: Prisma.ShiftReportUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>
        }
        deleteMany: {
          args: Prisma.ShiftReportDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ShiftReportUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ShiftReportUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>[]
        }
        upsert: {
          args: Prisma.ShiftReportUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ShiftReportPayload>
        }
        aggregate: {
          args: Prisma.ShiftReportAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateShiftReport>
        }
        groupBy: {
          args: Prisma.ShiftReportGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ShiftReportGroupByOutputType>[]
        }
        count: {
          args: Prisma.ShiftReportCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ShiftReportCountAggregateOutputType> | number
        }
      }
    }
    RestrictivePractice: {
      payload: Prisma.$RestrictivePracticePayload<ExtArgs>
      fields: Prisma.RestrictivePracticeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RestrictivePracticeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RestrictivePracticeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>
        }
        findFirst: {
          args: Prisma.RestrictivePracticeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RestrictivePracticeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>
        }
        findMany: {
          args: Prisma.RestrictivePracticeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>[]
        }
        create: {
          args: Prisma.RestrictivePracticeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>
        }
        createMany: {
          args: Prisma.RestrictivePracticeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RestrictivePracticeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>[]
        }
        delete: {
          args: Prisma.RestrictivePracticeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>
        }
        update: {
          args: Prisma.RestrictivePracticeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>
        }
        deleteMany: {
          args: Prisma.RestrictivePracticeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RestrictivePracticeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RestrictivePracticeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>[]
        }
        upsert: {
          args: Prisma.RestrictivePracticeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RestrictivePracticePayload>
        }
        aggregate: {
          args: Prisma.RestrictivePracticeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRestrictivePractice>
        }
        groupBy: {
          args: Prisma.RestrictivePracticeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RestrictivePracticeGroupByOutputType>[]
        }
        count: {
          args: Prisma.RestrictivePracticeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RestrictivePracticeCountAggregateOutputType> | number
        }
      }
    }
    Risk: {
      payload: Prisma.$RiskPayload<ExtArgs>
      fields: Prisma.RiskFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RiskFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RiskFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>
        }
        findFirst: {
          args: Prisma.RiskFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RiskFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>
        }
        findMany: {
          args: Prisma.RiskFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>[]
        }
        create: {
          args: Prisma.RiskCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>
        }
        createMany: {
          args: Prisma.RiskCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RiskCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>[]
        }
        delete: {
          args: Prisma.RiskDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>
        }
        update: {
          args: Prisma.RiskUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>
        }
        deleteMany: {
          args: Prisma.RiskDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RiskUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RiskUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>[]
        }
        upsert: {
          args: Prisma.RiskUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RiskPayload>
        }
        aggregate: {
          args: Prisma.RiskAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRisk>
        }
        groupBy: {
          args: Prisma.RiskGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RiskGroupByOutputType>[]
        }
        count: {
          args: Prisma.RiskCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RiskCountAggregateOutputType> | number
        }
      }
    }
    RegulatoryItem: {
      payload: Prisma.$RegulatoryItemPayload<ExtArgs>
      fields: Prisma.RegulatoryItemFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RegulatoryItemFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RegulatoryItemFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>
        }
        findFirst: {
          args: Prisma.RegulatoryItemFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RegulatoryItemFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>
        }
        findMany: {
          args: Prisma.RegulatoryItemFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>[]
        }
        create: {
          args: Prisma.RegulatoryItemCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>
        }
        createMany: {
          args: Prisma.RegulatoryItemCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RegulatoryItemCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>[]
        }
        delete: {
          args: Prisma.RegulatoryItemDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>
        }
        update: {
          args: Prisma.RegulatoryItemUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>
        }
        deleteMany: {
          args: Prisma.RegulatoryItemDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RegulatoryItemUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RegulatoryItemUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>[]
        }
        upsert: {
          args: Prisma.RegulatoryItemUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RegulatoryItemPayload>
        }
        aggregate: {
          args: Prisma.RegulatoryItemAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRegulatoryItem>
        }
        groupBy: {
          args: Prisma.RegulatoryItemGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RegulatoryItemGroupByOutputType>[]
        }
        count: {
          args: Prisma.RegulatoryItemCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RegulatoryItemCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ParticipantScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  dateOfBirth: 'dateOfBirth',
  gender: 'gender',
  address: 'address',
  ndisNumber: 'ndisNumber',
  planStartDate: 'planStartDate',
  planEndDate: 'planEndDate',
  planManagement: 'planManagement',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ParticipantScalarFieldEnum = (typeof ParticipantScalarFieldEnum)[keyof typeof ParticipantScalarFieldEnum]


export const EmergencyContactScalarFieldEnum = {
  id: 'id',
  name: 'name',
  relationship: 'relationship',
  phone: 'phone',
  email: 'email',
  participantId: 'participantId'
} as const

export type EmergencyContactScalarFieldEnum = (typeof EmergencyContactScalarFieldEnum)[keyof typeof EmergencyContactScalarFieldEnum]


export const StaffScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  role: 'role',
  status: 'status',
  wwccStatus: 'wwccStatus',
  wwccExpiry: 'wwccExpiry',
  firstAidStatus: 'firstAidStatus',
  firstAidExpiry: 'firstAidExpiry',
  ndisScreenStatus: 'ndisScreenStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StaffScalarFieldEnum = (typeof StaffScalarFieldEnum)[keyof typeof StaffScalarFieldEnum]


export const IncidentScalarFieldEnum = {
  id: 'id',
  date: 'date',
  time: 'time',
  location: 'location',
  type: 'type',
  description: 'description',
  immediateAction: 'immediateAction',
  severity: 'severity',
  status: 'status',
  participantId: 'participantId',
  staffId: 'staffId',
  managerNotified: 'managerNotified',
  restrictivePracticeUsed: 'restrictivePracticeUsed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type IncidentScalarFieldEnum = (typeof IncidentScalarFieldEnum)[keyof typeof IncidentScalarFieldEnum]


export const ShiftReportScalarFieldEnum = {
  id: 'id',
  date: 'date',
  shiftType: 'shiftType',
  startTime: 'startTime',
  endTime: 'endTime',
  mood: 'mood',
  medicationAdministered: 'medicationAdministered',
  notes: 'notes',
  handoverNotes: 'handoverNotes',
  incidentOccurred: 'incidentOccurred',
  participantId: 'participantId',
  staffId: 'staffId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ShiftReportScalarFieldEnum = (typeof ShiftReportScalarFieldEnum)[keyof typeof ShiftReportScalarFieldEnum]


export const RestrictivePracticeScalarFieldEnum = {
  id: 'id',
  type: 'type',
  isAuthorized: 'isAuthorized',
  startTime: 'startTime',
  endTime: 'endTime',
  reason: 'reason',
  strategies: 'strategies',
  staffInvolved: 'staffInvolved',
  participantId: 'participantId',
  createdAt: 'createdAt'
} as const

export type RestrictivePracticeScalarFieldEnum = (typeof RestrictivePracticeScalarFieldEnum)[keyof typeof RestrictivePracticeScalarFieldEnum]


export const RiskScalarFieldEnum = {
  id: 'id',
  description: 'description',
  probability: 'probability',
  impact: 'impact',
  mitigation: 'mitigation',
  status: 'status',
  participantId: 'participantId',
  createdAt: 'createdAt'
} as const

export type RiskScalarFieldEnum = (typeof RiskScalarFieldEnum)[keyof typeof RiskScalarFieldEnum]


export const RegulatoryItemScalarFieldEnum = {
  id: 'id',
  standard: 'standard',
  requirement: 'requirement',
  status: 'status',
  lastAudit: 'lastAudit'
} as const

export type RegulatoryItemScalarFieldEnum = (typeof RegulatoryItemScalarFieldEnum)[keyof typeof RegulatoryItemScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
}
export type GlobalOmitConfig = {
  participant?: Prisma.ParticipantOmit
  emergencyContact?: Prisma.EmergencyContactOmit
  staff?: Prisma.StaffOmit
  incident?: Prisma.IncidentOmit
  shiftReport?: Prisma.ShiftReportOmit
  restrictivePractice?: Prisma.RestrictivePracticeOmit
  risk?: Prisma.RiskOmit
  regulatoryItem?: Prisma.RegulatoryItemOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

