
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Participant: 'Participant',
  EmergencyContact: 'EmergencyContact',
  Staff: 'Staff',
  Incident: 'Incident',
  ShiftReport: 'ShiftReport',
  RestrictivePractice: 'RestrictivePractice',
  Risk: 'Risk',
  RegulatoryItem: 'RegulatoryItem'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const ParticipantScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  dateOfBirth: 'dateOfBirth',
  gender: 'gender',
  address: 'address',
  ndisNumber: 'ndisNumber',
  planStartDate: 'planStartDate',
  planEndDate: 'planEndDate',
  planManagement: 'planManagement',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ParticipantScalarFieldEnum = (typeof ParticipantScalarFieldEnum)[keyof typeof ParticipantScalarFieldEnum]


export const EmergencyContactScalarFieldEnum = {
  id: 'id',
  name: 'name',
  relationship: 'relationship',
  phone: 'phone',
  email: 'email',
  participantId: 'participantId'
} as const

export type EmergencyContactScalarFieldEnum = (typeof EmergencyContactScalarFieldEnum)[keyof typeof EmergencyContactScalarFieldEnum]


export const StaffScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  role: 'role',
  status: 'status',
  wwccStatus: 'wwccStatus',
  wwccExpiry: 'wwccExpiry',
  firstAidStatus: 'firstAidStatus',
  firstAidExpiry: 'firstAidExpiry',
  ndisScreenStatus: 'ndisScreenStatus',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StaffScalarFieldEnum = (typeof StaffScalarFieldEnum)[keyof typeof StaffScalarFieldEnum]


export const IncidentScalarFieldEnum = {
  id: 'id',
  date: 'date',
  time: 'time',
  location: 'location',
  type: 'type',
  description: 'description',
  immediateAction: 'immediateAction',
  severity: 'severity',
  status: 'status',
  participantId: 'participantId',
  staffId: 'staffId',
  managerNotified: 'managerNotified',
  restrictivePracticeUsed: 'restrictivePracticeUsed',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type IncidentScalarFieldEnum = (typeof IncidentScalarFieldEnum)[keyof typeof IncidentScalarFieldEnum]


export const ShiftReportScalarFieldEnum = {
  id: 'id',
  date: 'date',
  shiftType: 'shiftType',
  startTime: 'startTime',
  endTime: 'endTime',
  mood: 'mood',
  medicationAdministered: 'medicationAdministered',
  notes: 'notes',
  handoverNotes: 'handoverNotes',
  incidentOccurred: 'incidentOccurred',
  participantId: 'participantId',
  staffId: 'staffId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ShiftReportScalarFieldEnum = (typeof ShiftReportScalarFieldEnum)[keyof typeof ShiftReportScalarFieldEnum]


export const RestrictivePracticeScalarFieldEnum = {
  id: 'id',
  type: 'type',
  isAuthorized: 'isAuthorized',
  startTime: 'startTime',
  endTime: 'endTime',
  reason: 'reason',
  strategies: 'strategies',
  staffInvolved: 'staffInvolved',
  participantId: 'participantId',
  createdAt: 'createdAt'
} as const

export type RestrictivePracticeScalarFieldEnum = (typeof RestrictivePracticeScalarFieldEnum)[keyof typeof RestrictivePracticeScalarFieldEnum]


export const RiskScalarFieldEnum = {
  id: 'id',
  description: 'description',
  probability: 'probability',
  impact: 'impact',
  mitigation: 'mitigation',
  status: 'status',
  participantId: 'participantId',
  createdAt: 'createdAt'
} as const

export type RiskScalarFieldEnum = (typeof RiskScalarFieldEnum)[keyof typeof RiskScalarFieldEnum]


export const RegulatoryItemScalarFieldEnum = {
  id: 'id',
  standard: 'standard',
  requirement: 'requirement',
  status: 'status',
  lastAudit: 'lastAudit'
} as const

export type RegulatoryItemScalarFieldEnum = (typeof RegulatoryItemScalarFieldEnum)[keyof typeof RegulatoryItemScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

