
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Participant` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Participant
 * 
 */
export type ParticipantModel = runtime.Types.Result.DefaultSelection<Prisma.$ParticipantPayload>

export type AggregateParticipant = {
  _count: ParticipantCountAggregateOutputType | null
  _min: ParticipantMinAggregateOutputType | null
  _max: ParticipantMaxAggregateOutputType | null
}

export type ParticipantMinAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  dateOfBirth: Date | null
  gender: string | null
  address: string | null
  ndisNumber: string | null
  planStartDate: Date | null
  planEndDate: Date | null
  planManagement: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ParticipantMaxAggregateOutputType = {
  id: string | null
  firstName: string | null
  lastName: string | null
  dateOfBirth: Date | null
  gender: string | null
  address: string | null
  ndisNumber: string | null
  planStartDate: Date | null
  planEndDate: Date | null
  planManagement: string | null
  status: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ParticipantCountAggregateOutputType = {
  id: number
  firstName: number
  lastName: number
  dateOfBirth: number
  gender: number
  address: number
  ndisNumber: number
  planStartDate: number
  planEndDate: number
  planManagement: number
  status: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ParticipantMinAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  dateOfBirth?: true
  gender?: true
  address?: true
  ndisNumber?: true
  planStartDate?: true
  planEndDate?: true
  planManagement?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ParticipantMaxAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  dateOfBirth?: true
  gender?: true
  address?: true
  ndisNumber?: true
  planStartDate?: true
  planEndDate?: true
  planManagement?: true
  status?: true
  createdAt?: true
  updatedAt?: true
}

export type ParticipantCountAggregateInputType = {
  id?: true
  firstName?: true
  lastName?: true
  dateOfBirth?: true
  gender?: true
  address?: true
  ndisNumber?: true
  planStartDate?: true
  planEndDate?: true
  planManagement?: true
  status?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ParticipantAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Participant to aggregate.
   */
  where?: Prisma.ParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participants to fetch.
   */
  orderBy?: Prisma.ParticipantOrderByWithRelationInput | Prisma.ParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Participants
  **/
  _count?: true | ParticipantCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ParticipantMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ParticipantMaxAggregateInputType
}

export type GetParticipantAggregateType<T extends ParticipantAggregateArgs> = {
      [P in keyof T & keyof AggregateParticipant]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateParticipant[P]>
    : Prisma.GetScalarType<T[P], AggregateParticipant[P]>
}




export type ParticipantGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParticipantWhereInput
  orderBy?: Prisma.ParticipantOrderByWithAggregationInput | Prisma.ParticipantOrderByWithAggregationInput[]
  by: Prisma.ParticipantScalarFieldEnum[] | Prisma.ParticipantScalarFieldEnum
  having?: Prisma.ParticipantScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ParticipantCountAggregateInputType | true
  _min?: ParticipantMinAggregateInputType
  _max?: ParticipantMaxAggregateInputType
}

export type ParticipantGroupByOutputType = {
  id: string
  firstName: string
  lastName: string
  dateOfBirth: Date
  gender: string
  address: string | null
  ndisNumber: string | null
  planStartDate: Date | null
  planEndDate: Date | null
  planManagement: string | null
  status: string
  createdAt: Date
  updatedAt: Date
  _count: ParticipantCountAggregateOutputType | null
  _min: ParticipantMinAggregateOutputType | null
  _max: ParticipantMaxAggregateOutputType | null
}

type GetParticipantGroupByPayload<T extends ParticipantGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ParticipantGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ParticipantGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ParticipantGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ParticipantGroupByOutputType[P]>
      }
    >
  >



export type ParticipantWhereInput = {
  AND?: Prisma.ParticipantWhereInput | Prisma.ParticipantWhereInput[]
  OR?: Prisma.ParticipantWhereInput[]
  NOT?: Prisma.ParticipantWhereInput | Prisma.ParticipantWhereInput[]
  id?: Prisma.StringFilter<"Participant"> | string
  firstName?: Prisma.StringFilter<"Participant"> | string
  lastName?: Prisma.StringFilter<"Participant"> | string
  dateOfBirth?: Prisma.DateTimeFilter<"Participant"> | Date | string
  gender?: Prisma.StringFilter<"Participant"> | string
  address?: Prisma.StringNullableFilter<"Participant"> | string | null
  ndisNumber?: Prisma.StringNullableFilter<"Participant"> | string | null
  planStartDate?: Prisma.DateTimeNullableFilter<"Participant"> | Date | string | null
  planEndDate?: Prisma.DateTimeNullableFilter<"Participant"> | Date | string | null
  planManagement?: Prisma.StringNullableFilter<"Participant"> | string | null
  status?: Prisma.StringFilter<"Participant"> | string
  createdAt?: Prisma.DateTimeFilter<"Participant"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Participant"> | Date | string
  contacts?: Prisma.EmergencyContactListRelationFilter
  incidents?: Prisma.IncidentListRelationFilter
  shiftReports?: Prisma.ShiftReportListRelationFilter
  risks?: Prisma.RiskListRelationFilter
  restrictivePractices?: Prisma.RestrictivePracticeListRelationFilter
}

export type ParticipantOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  ndisNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  planStartDate?: Prisma.SortOrderInput | Prisma.SortOrder
  planEndDate?: Prisma.SortOrderInput | Prisma.SortOrder
  planManagement?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  contacts?: Prisma.EmergencyContactOrderByRelationAggregateInput
  incidents?: Prisma.IncidentOrderByRelationAggregateInput
  shiftReports?: Prisma.ShiftReportOrderByRelationAggregateInput
  risks?: Prisma.RiskOrderByRelationAggregateInput
  restrictivePractices?: Prisma.RestrictivePracticeOrderByRelationAggregateInput
}

export type ParticipantWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ParticipantWhereInput | Prisma.ParticipantWhereInput[]
  OR?: Prisma.ParticipantWhereInput[]
  NOT?: Prisma.ParticipantWhereInput | Prisma.ParticipantWhereInput[]
  firstName?: Prisma.StringFilter<"Participant"> | string
  lastName?: Prisma.StringFilter<"Participant"> | string
  dateOfBirth?: Prisma.DateTimeFilter<"Participant"> | Date | string
  gender?: Prisma.StringFilter<"Participant"> | string
  address?: Prisma.StringNullableFilter<"Participant"> | string | null
  ndisNumber?: Prisma.StringNullableFilter<"Participant"> | string | null
  planStartDate?: Prisma.DateTimeNullableFilter<"Participant"> | Date | string | null
  planEndDate?: Prisma.DateTimeNullableFilter<"Participant"> | Date | string | null
  planManagement?: Prisma.StringNullableFilter<"Participant"> | string | null
  status?: Prisma.StringFilter<"Participant"> | string
  createdAt?: Prisma.DateTimeFilter<"Participant"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Participant"> | Date | string
  contacts?: Prisma.EmergencyContactListRelationFilter
  incidents?: Prisma.IncidentListRelationFilter
  shiftReports?: Prisma.ShiftReportListRelationFilter
  risks?: Prisma.RiskListRelationFilter
  restrictivePractices?: Prisma.RestrictivePracticeListRelationFilter
}, "id">

export type ParticipantOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  ndisNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  planStartDate?: Prisma.SortOrderInput | Prisma.SortOrder
  planEndDate?: Prisma.SortOrderInput | Prisma.SortOrder
  planManagement?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ParticipantCountOrderByAggregateInput
  _max?: Prisma.ParticipantMaxOrderByAggregateInput
  _min?: Prisma.ParticipantMinOrderByAggregateInput
}

export type ParticipantScalarWhereWithAggregatesInput = {
  AND?: Prisma.ParticipantScalarWhereWithAggregatesInput | Prisma.ParticipantScalarWhereWithAggregatesInput[]
  OR?: Prisma.ParticipantScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ParticipantScalarWhereWithAggregatesInput | Prisma.ParticipantScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Participant"> | string
  firstName?: Prisma.StringWithAggregatesFilter<"Participant"> | string
  lastName?: Prisma.StringWithAggregatesFilter<"Participant"> | string
  dateOfBirth?: Prisma.DateTimeWithAggregatesFilter<"Participant"> | Date | string
  gender?: Prisma.StringWithAggregatesFilter<"Participant"> | string
  address?: Prisma.StringNullableWithAggregatesFilter<"Participant"> | string | null
  ndisNumber?: Prisma.StringNullableWithAggregatesFilter<"Participant"> | string | null
  planStartDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Participant"> | Date | string | null
  planEndDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Participant"> | Date | string | null
  planManagement?: Prisma.StringNullableWithAggregatesFilter<"Participant"> | string | null
  status?: Prisma.StringWithAggregatesFilter<"Participant"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Participant"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Participant"> | Date | string
}

export type ParticipantCreateInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeCreateNestedManyWithoutParticipantInput
}

export type ParticipantUncheckedCreateInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactUncheckedCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportUncheckedCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskUncheckedCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedCreateNestedManyWithoutParticipantInput
}

export type ParticipantUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUpdateManyWithoutParticipantNestedInput
}

export type ParticipantUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUncheckedUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUncheckedUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUncheckedUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedUpdateManyWithoutParticipantNestedInput
}

export type ParticipantCreateManyInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ParticipantUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ParticipantCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  ndisNumber?: Prisma.SortOrder
  planStartDate?: Prisma.SortOrder
  planEndDate?: Prisma.SortOrder
  planManagement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ParticipantMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  ndisNumber?: Prisma.SortOrder
  planStartDate?: Prisma.SortOrder
  planEndDate?: Prisma.SortOrder
  planManagement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ParticipantMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  firstName?: Prisma.SortOrder
  lastName?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  address?: Prisma.SortOrder
  ndisNumber?: Prisma.SortOrder
  planStartDate?: Prisma.SortOrder
  planEndDate?: Prisma.SortOrder
  planManagement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ParticipantScalarRelationFilter = {
  is?: Prisma.ParticipantWhereInput
  isNot?: Prisma.ParticipantWhereInput
}

export type ParticipantNullableScalarRelationFilter = {
  is?: Prisma.ParticipantWhereInput | null
  isNot?: Prisma.ParticipantWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ParticipantCreateNestedOneWithoutContactsInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutContactsInput, Prisma.ParticipantUncheckedCreateWithoutContactsInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutContactsInput
  connect?: Prisma.ParticipantWhereUniqueInput
}

export type ParticipantUpdateOneRequiredWithoutContactsNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutContactsInput, Prisma.ParticipantUncheckedCreateWithoutContactsInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutContactsInput
  upsert?: Prisma.ParticipantUpsertWithoutContactsInput
  connect?: Prisma.ParticipantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ParticipantUpdateToOneWithWhereWithoutContactsInput, Prisma.ParticipantUpdateWithoutContactsInput>, Prisma.ParticipantUncheckedUpdateWithoutContactsInput>
}

export type ParticipantCreateNestedOneWithoutIncidentsInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutIncidentsInput, Prisma.ParticipantUncheckedCreateWithoutIncidentsInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutIncidentsInput
  connect?: Prisma.ParticipantWhereUniqueInput
}

export type ParticipantUpdateOneWithoutIncidentsNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutIncidentsInput, Prisma.ParticipantUncheckedCreateWithoutIncidentsInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutIncidentsInput
  upsert?: Prisma.ParticipantUpsertWithoutIncidentsInput
  disconnect?: Prisma.ParticipantWhereInput | boolean
  delete?: Prisma.ParticipantWhereInput | boolean
  connect?: Prisma.ParticipantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ParticipantUpdateToOneWithWhereWithoutIncidentsInput, Prisma.ParticipantUpdateWithoutIncidentsInput>, Prisma.ParticipantUncheckedUpdateWithoutIncidentsInput>
}

export type ParticipantCreateNestedOneWithoutShiftReportsInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutShiftReportsInput, Prisma.ParticipantUncheckedCreateWithoutShiftReportsInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutShiftReportsInput
  connect?: Prisma.ParticipantWhereUniqueInput
}

export type ParticipantUpdateOneWithoutShiftReportsNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutShiftReportsInput, Prisma.ParticipantUncheckedCreateWithoutShiftReportsInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutShiftReportsInput
  upsert?: Prisma.ParticipantUpsertWithoutShiftReportsInput
  disconnect?: Prisma.ParticipantWhereInput | boolean
  delete?: Prisma.ParticipantWhereInput | boolean
  connect?: Prisma.ParticipantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ParticipantUpdateToOneWithWhereWithoutShiftReportsInput, Prisma.ParticipantUpdateWithoutShiftReportsInput>, Prisma.ParticipantUncheckedUpdateWithoutShiftReportsInput>
}

export type ParticipantCreateNestedOneWithoutRestrictivePracticesInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutRestrictivePracticesInput, Prisma.ParticipantUncheckedCreateWithoutRestrictivePracticesInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutRestrictivePracticesInput
  connect?: Prisma.ParticipantWhereUniqueInput
}

export type ParticipantUpdateOneRequiredWithoutRestrictivePracticesNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutRestrictivePracticesInput, Prisma.ParticipantUncheckedCreateWithoutRestrictivePracticesInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutRestrictivePracticesInput
  upsert?: Prisma.ParticipantUpsertWithoutRestrictivePracticesInput
  connect?: Prisma.ParticipantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ParticipantUpdateToOneWithWhereWithoutRestrictivePracticesInput, Prisma.ParticipantUpdateWithoutRestrictivePracticesInput>, Prisma.ParticipantUncheckedUpdateWithoutRestrictivePracticesInput>
}

export type ParticipantCreateNestedOneWithoutRisksInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutRisksInput, Prisma.ParticipantUncheckedCreateWithoutRisksInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutRisksInput
  connect?: Prisma.ParticipantWhereUniqueInput
}

export type ParticipantUpdateOneWithoutRisksNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipantCreateWithoutRisksInput, Prisma.ParticipantUncheckedCreateWithoutRisksInput>
  connectOrCreate?: Prisma.ParticipantCreateOrConnectWithoutRisksInput
  upsert?: Prisma.ParticipantUpsertWithoutRisksInput
  disconnect?: Prisma.ParticipantWhereInput | boolean
  delete?: Prisma.ParticipantWhereInput | boolean
  connect?: Prisma.ParticipantWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ParticipantUpdateToOneWithWhereWithoutRisksInput, Prisma.ParticipantUpdateWithoutRisksInput>, Prisma.ParticipantUncheckedUpdateWithoutRisksInput>
}

export type ParticipantCreateWithoutContactsInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  incidents?: Prisma.IncidentCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeCreateNestedManyWithoutParticipantInput
}

export type ParticipantUncheckedCreateWithoutContactsInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportUncheckedCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskUncheckedCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedCreateNestedManyWithoutParticipantInput
}

export type ParticipantCreateOrConnectWithoutContactsInput = {
  where: Prisma.ParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutContactsInput, Prisma.ParticipantUncheckedCreateWithoutContactsInput>
}

export type ParticipantUpsertWithoutContactsInput = {
  update: Prisma.XOR<Prisma.ParticipantUpdateWithoutContactsInput, Prisma.ParticipantUncheckedUpdateWithoutContactsInput>
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutContactsInput, Prisma.ParticipantUncheckedCreateWithoutContactsInput>
  where?: Prisma.ParticipantWhereInput
}

export type ParticipantUpdateToOneWithWhereWithoutContactsInput = {
  where?: Prisma.ParticipantWhereInput
  data: Prisma.XOR<Prisma.ParticipantUpdateWithoutContactsInput, Prisma.ParticipantUncheckedUpdateWithoutContactsInput>
}

export type ParticipantUpdateWithoutContactsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  incidents?: Prisma.IncidentUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUpdateManyWithoutParticipantNestedInput
}

export type ParticipantUncheckedUpdateWithoutContactsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUncheckedUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUncheckedUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedUpdateManyWithoutParticipantNestedInput
}

export type ParticipantCreateWithoutIncidentsInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeCreateNestedManyWithoutParticipantInput
}

export type ParticipantUncheckedCreateWithoutIncidentsInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactUncheckedCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportUncheckedCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskUncheckedCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedCreateNestedManyWithoutParticipantInput
}

export type ParticipantCreateOrConnectWithoutIncidentsInput = {
  where: Prisma.ParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutIncidentsInput, Prisma.ParticipantUncheckedCreateWithoutIncidentsInput>
}

export type ParticipantUpsertWithoutIncidentsInput = {
  update: Prisma.XOR<Prisma.ParticipantUpdateWithoutIncidentsInput, Prisma.ParticipantUncheckedUpdateWithoutIncidentsInput>
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutIncidentsInput, Prisma.ParticipantUncheckedCreateWithoutIncidentsInput>
  where?: Prisma.ParticipantWhereInput
}

export type ParticipantUpdateToOneWithWhereWithoutIncidentsInput = {
  where?: Prisma.ParticipantWhereInput
  data: Prisma.XOR<Prisma.ParticipantUpdateWithoutIncidentsInput, Prisma.ParticipantUncheckedUpdateWithoutIncidentsInput>
}

export type ParticipantUpdateWithoutIncidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUpdateManyWithoutParticipantNestedInput
}

export type ParticipantUncheckedUpdateWithoutIncidentsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUncheckedUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUncheckedUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUncheckedUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedUpdateManyWithoutParticipantNestedInput
}

export type ParticipantCreateWithoutShiftReportsInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeCreateNestedManyWithoutParticipantInput
}

export type ParticipantUncheckedCreateWithoutShiftReportsInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactUncheckedCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskUncheckedCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedCreateNestedManyWithoutParticipantInput
}

export type ParticipantCreateOrConnectWithoutShiftReportsInput = {
  where: Prisma.ParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutShiftReportsInput, Prisma.ParticipantUncheckedCreateWithoutShiftReportsInput>
}

export type ParticipantUpsertWithoutShiftReportsInput = {
  update: Prisma.XOR<Prisma.ParticipantUpdateWithoutShiftReportsInput, Prisma.ParticipantUncheckedUpdateWithoutShiftReportsInput>
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutShiftReportsInput, Prisma.ParticipantUncheckedCreateWithoutShiftReportsInput>
  where?: Prisma.ParticipantWhereInput
}

export type ParticipantUpdateToOneWithWhereWithoutShiftReportsInput = {
  where?: Prisma.ParticipantWhereInput
  data: Prisma.XOR<Prisma.ParticipantUpdateWithoutShiftReportsInput, Prisma.ParticipantUncheckedUpdateWithoutShiftReportsInput>
}

export type ParticipantUpdateWithoutShiftReportsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUpdateManyWithoutParticipantNestedInput
}

export type ParticipantUncheckedUpdateWithoutShiftReportsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUncheckedUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUncheckedUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedUpdateManyWithoutParticipantNestedInput
}

export type ParticipantCreateWithoutRestrictivePracticesInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskCreateNestedManyWithoutParticipantInput
}

export type ParticipantUncheckedCreateWithoutRestrictivePracticesInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactUncheckedCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportUncheckedCreateNestedManyWithoutParticipantInput
  risks?: Prisma.RiskUncheckedCreateNestedManyWithoutParticipantInput
}

export type ParticipantCreateOrConnectWithoutRestrictivePracticesInput = {
  where: Prisma.ParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutRestrictivePracticesInput, Prisma.ParticipantUncheckedCreateWithoutRestrictivePracticesInput>
}

export type ParticipantUpsertWithoutRestrictivePracticesInput = {
  update: Prisma.XOR<Prisma.ParticipantUpdateWithoutRestrictivePracticesInput, Prisma.ParticipantUncheckedUpdateWithoutRestrictivePracticesInput>
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutRestrictivePracticesInput, Prisma.ParticipantUncheckedCreateWithoutRestrictivePracticesInput>
  where?: Prisma.ParticipantWhereInput
}

export type ParticipantUpdateToOneWithWhereWithoutRestrictivePracticesInput = {
  where?: Prisma.ParticipantWhereInput
  data: Prisma.XOR<Prisma.ParticipantUpdateWithoutRestrictivePracticesInput, Prisma.ParticipantUncheckedUpdateWithoutRestrictivePracticesInput>
}

export type ParticipantUpdateWithoutRestrictivePracticesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUpdateManyWithoutParticipantNestedInput
}

export type ParticipantUncheckedUpdateWithoutRestrictivePracticesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUncheckedUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUncheckedUpdateManyWithoutParticipantNestedInput
  risks?: Prisma.RiskUncheckedUpdateManyWithoutParticipantNestedInput
}

export type ParticipantCreateWithoutRisksInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeCreateNestedManyWithoutParticipantInput
}

export type ParticipantUncheckedCreateWithoutRisksInput = {
  id?: string
  firstName: string
  lastName: string
  dateOfBirth: Date | string
  gender: string
  address?: string | null
  ndisNumber?: string | null
  planStartDate?: Date | string | null
  planEndDate?: Date | string | null
  planManagement?: string | null
  status?: string
  createdAt?: Date | string
  updatedAt?: Date | string
  contacts?: Prisma.EmergencyContactUncheckedCreateNestedManyWithoutParticipantInput
  incidents?: Prisma.IncidentUncheckedCreateNestedManyWithoutParticipantInput
  shiftReports?: Prisma.ShiftReportUncheckedCreateNestedManyWithoutParticipantInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedCreateNestedManyWithoutParticipantInput
}

export type ParticipantCreateOrConnectWithoutRisksInput = {
  where: Prisma.ParticipantWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutRisksInput, Prisma.ParticipantUncheckedCreateWithoutRisksInput>
}

export type ParticipantUpsertWithoutRisksInput = {
  update: Prisma.XOR<Prisma.ParticipantUpdateWithoutRisksInput, Prisma.ParticipantUncheckedUpdateWithoutRisksInput>
  create: Prisma.XOR<Prisma.ParticipantCreateWithoutRisksInput, Prisma.ParticipantUncheckedCreateWithoutRisksInput>
  where?: Prisma.ParticipantWhereInput
}

export type ParticipantUpdateToOneWithWhereWithoutRisksInput = {
  where?: Prisma.ParticipantWhereInput
  data: Prisma.XOR<Prisma.ParticipantUpdateWithoutRisksInput, Prisma.ParticipantUncheckedUpdateWithoutRisksInput>
}

export type ParticipantUpdateWithoutRisksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUpdateManyWithoutParticipantNestedInput
}

export type ParticipantUncheckedUpdateWithoutRisksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  firstName?: Prisma.StringFieldUpdateOperationsInput | string
  lastName?: Prisma.StringFieldUpdateOperationsInput | string
  dateOfBirth?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  gender?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ndisNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  planStartDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planEndDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  planManagement?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contacts?: Prisma.EmergencyContactUncheckedUpdateManyWithoutParticipantNestedInput
  incidents?: Prisma.IncidentUncheckedUpdateManyWithoutParticipantNestedInput
  shiftReports?: Prisma.ShiftReportUncheckedUpdateManyWithoutParticipantNestedInput
  restrictivePractices?: Prisma.RestrictivePracticeUncheckedUpdateManyWithoutParticipantNestedInput
}


/**
 * Count Type ParticipantCountOutputType
 */

export type ParticipantCountOutputType = {
  contacts: number
  incidents: number
  shiftReports: number
  risks: number
  restrictivePractices: number
}

export type ParticipantCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contacts?: boolean | ParticipantCountOutputTypeCountContactsArgs
  incidents?: boolean | ParticipantCountOutputTypeCountIncidentsArgs
  shiftReports?: boolean | ParticipantCountOutputTypeCountShiftReportsArgs
  risks?: boolean | ParticipantCountOutputTypeCountRisksArgs
  restrictivePractices?: boolean | ParticipantCountOutputTypeCountRestrictivePracticesArgs
}

/**
 * ParticipantCountOutputType without action
 */
export type ParticipantCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipantCountOutputType
   */
  select?: Prisma.ParticipantCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ParticipantCountOutputType without action
 */
export type ParticipantCountOutputTypeCountContactsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmergencyContactWhereInput
}

/**
 * ParticipantCountOutputType without action
 */
export type ParticipantCountOutputTypeCountIncidentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncidentWhereInput
}

/**
 * ParticipantCountOutputType without action
 */
export type ParticipantCountOutputTypeCountShiftReportsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShiftReportWhereInput
}

/**
 * ParticipantCountOutputType without action
 */
export type ParticipantCountOutputTypeCountRisksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RiskWhereInput
}

/**
 * ParticipantCountOutputType without action
 */
export type ParticipantCountOutputTypeCountRestrictivePracticesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RestrictivePracticeWhereInput
}


export type ParticipantSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  dateOfBirth?: boolean
  gender?: boolean
  address?: boolean
  ndisNumber?: boolean
  planStartDate?: boolean
  planEndDate?: boolean
  planManagement?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  contacts?: boolean | Prisma.Participant$contactsArgs<ExtArgs>
  incidents?: boolean | Prisma.Participant$incidentsArgs<ExtArgs>
  shiftReports?: boolean | Prisma.Participant$shiftReportsArgs<ExtArgs>
  risks?: boolean | Prisma.Participant$risksArgs<ExtArgs>
  restrictivePractices?: boolean | Prisma.Participant$restrictivePracticesArgs<ExtArgs>
  _count?: boolean | Prisma.ParticipantCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["participant"]>

export type ParticipantSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  dateOfBirth?: boolean
  gender?: boolean
  address?: boolean
  ndisNumber?: boolean
  planStartDate?: boolean
  planEndDate?: boolean
  planManagement?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["participant"]>

export type ParticipantSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  dateOfBirth?: boolean
  gender?: boolean
  address?: boolean
  ndisNumber?: boolean
  planStartDate?: boolean
  planEndDate?: boolean
  planManagement?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["participant"]>

export type ParticipantSelectScalar = {
  id?: boolean
  firstName?: boolean
  lastName?: boolean
  dateOfBirth?: boolean
  gender?: boolean
  address?: boolean
  ndisNumber?: boolean
  planStartDate?: boolean
  planEndDate?: boolean
  planManagement?: boolean
  status?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ParticipantOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "firstName" | "lastName" | "dateOfBirth" | "gender" | "address" | "ndisNumber" | "planStartDate" | "planEndDate" | "planManagement" | "status" | "createdAt" | "updatedAt", ExtArgs["result"]["participant"]>
export type ParticipantInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contacts?: boolean | Prisma.Participant$contactsArgs<ExtArgs>
  incidents?: boolean | Prisma.Participant$incidentsArgs<ExtArgs>
  shiftReports?: boolean | Prisma.Participant$shiftReportsArgs<ExtArgs>
  risks?: boolean | Prisma.Participant$risksArgs<ExtArgs>
  restrictivePractices?: boolean | Prisma.Participant$restrictivePracticesArgs<ExtArgs>
  _count?: boolean | Prisma.ParticipantCountOutputTypeDefaultArgs<ExtArgs>
}
export type ParticipantIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type ParticipantIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ParticipantPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Participant"
  objects: {
    contacts: Prisma.$EmergencyContactPayload<ExtArgs>[]
    incidents: Prisma.$IncidentPayload<ExtArgs>[]
    shiftReports: Prisma.$ShiftReportPayload<ExtArgs>[]
    risks: Prisma.$RiskPayload<ExtArgs>[]
    restrictivePractices: Prisma.$RestrictivePracticePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    firstName: string
    lastName: string
    dateOfBirth: Date
    gender: string
    address: string | null
    ndisNumber: string | null
    planStartDate: Date | null
    planEndDate: Date | null
    planManagement: string | null
    status: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["participant"]>
  composites: {}
}

export type ParticipantGetPayload<S extends boolean | null | undefined | ParticipantDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ParticipantPayload, S>

export type ParticipantCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ParticipantFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ParticipantCountAggregateInputType | true
  }

export interface ParticipantDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Participant'], meta: { name: 'Participant' } }
  /**
   * Find zero or one Participant that matches the filter.
   * @param {ParticipantFindUniqueArgs} args - Arguments to find a Participant
   * @example
   * // Get one Participant
   * const participant = await prisma.participant.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ParticipantFindUniqueArgs>(args: Prisma.SelectSubset<T, ParticipantFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Participant that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ParticipantFindUniqueOrThrowArgs} args - Arguments to find a Participant
   * @example
   * // Get one Participant
   * const participant = await prisma.participant.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ParticipantFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ParticipantFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Participant that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantFindFirstArgs} args - Arguments to find a Participant
   * @example
   * // Get one Participant
   * const participant = await prisma.participant.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ParticipantFindFirstArgs>(args?: Prisma.SelectSubset<T, ParticipantFindFirstArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Participant that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantFindFirstOrThrowArgs} args - Arguments to find a Participant
   * @example
   * // Get one Participant
   * const participant = await prisma.participant.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ParticipantFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ParticipantFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Participants that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Participants
   * const participants = await prisma.participant.findMany()
   * 
   * // Get first 10 Participants
   * const participants = await prisma.participant.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const participantWithIdOnly = await prisma.participant.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ParticipantFindManyArgs>(args?: Prisma.SelectSubset<T, ParticipantFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Participant.
   * @param {ParticipantCreateArgs} args - Arguments to create a Participant.
   * @example
   * // Create one Participant
   * const Participant = await prisma.participant.create({
   *   data: {
   *     // ... data to create a Participant
   *   }
   * })
   * 
   */
  create<T extends ParticipantCreateArgs>(args: Prisma.SelectSubset<T, ParticipantCreateArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Participants.
   * @param {ParticipantCreateManyArgs} args - Arguments to create many Participants.
   * @example
   * // Create many Participants
   * const participant = await prisma.participant.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ParticipantCreateManyArgs>(args?: Prisma.SelectSubset<T, ParticipantCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Participants and returns the data saved in the database.
   * @param {ParticipantCreateManyAndReturnArgs} args - Arguments to create many Participants.
   * @example
   * // Create many Participants
   * const participant = await prisma.participant.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Participants and only return the `id`
   * const participantWithIdOnly = await prisma.participant.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ParticipantCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ParticipantCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Participant.
   * @param {ParticipantDeleteArgs} args - Arguments to delete one Participant.
   * @example
   * // Delete one Participant
   * const Participant = await prisma.participant.delete({
   *   where: {
   *     // ... filter to delete one Participant
   *   }
   * })
   * 
   */
  delete<T extends ParticipantDeleteArgs>(args: Prisma.SelectSubset<T, ParticipantDeleteArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Participant.
   * @param {ParticipantUpdateArgs} args - Arguments to update one Participant.
   * @example
   * // Update one Participant
   * const participant = await prisma.participant.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ParticipantUpdateArgs>(args: Prisma.SelectSubset<T, ParticipantUpdateArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Participants.
   * @param {ParticipantDeleteManyArgs} args - Arguments to filter Participants to delete.
   * @example
   * // Delete a few Participants
   * const { count } = await prisma.participant.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ParticipantDeleteManyArgs>(args?: Prisma.SelectSubset<T, ParticipantDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Participants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Participants
   * const participant = await prisma.participant.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ParticipantUpdateManyArgs>(args: Prisma.SelectSubset<T, ParticipantUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Participants and returns the data updated in the database.
   * @param {ParticipantUpdateManyAndReturnArgs} args - Arguments to update many Participants.
   * @example
   * // Update many Participants
   * const participant = await prisma.participant.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Participants and only return the `id`
   * const participantWithIdOnly = await prisma.participant.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ParticipantUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ParticipantUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Participant.
   * @param {ParticipantUpsertArgs} args - Arguments to update or create a Participant.
   * @example
   * // Update or create a Participant
   * const participant = await prisma.participant.upsert({
   *   create: {
   *     // ... data to create a Participant
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Participant we want to update
   *   }
   * })
   */
  upsert<T extends ParticipantUpsertArgs>(args: Prisma.SelectSubset<T, ParticipantUpsertArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Participants.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantCountArgs} args - Arguments to filter Participants to count.
   * @example
   * // Count the number of Participants
   * const count = await prisma.participant.count({
   *   where: {
   *     // ... the filter for the Participants we want to count
   *   }
   * })
  **/
  count<T extends ParticipantCountArgs>(
    args?: Prisma.Subset<T, ParticipantCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ParticipantCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Participant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ParticipantAggregateArgs>(args: Prisma.Subset<T, ParticipantAggregateArgs>): Prisma.PrismaPromise<GetParticipantAggregateType<T>>

  /**
   * Group by Participant.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipantGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ParticipantGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ParticipantGroupByArgs['orderBy'] }
      : { orderBy?: ParticipantGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ParticipantGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetParticipantGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Participant model
 */
readonly fields: ParticipantFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Participant.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ParticipantClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  contacts<T extends Prisma.Participant$contactsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Participant$contactsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmergencyContactPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  incidents<T extends Prisma.Participant$incidentsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Participant$incidentsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  shiftReports<T extends Prisma.Participant$shiftReportsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Participant$shiftReportsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  risks<T extends Prisma.Participant$risksArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Participant$risksArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RiskPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  restrictivePractices<T extends Prisma.Participant$restrictivePracticesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Participant$restrictivePracticesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Participant model
 */
export interface ParticipantFieldRefs {
  readonly id: Prisma.FieldRef<"Participant", 'String'>
  readonly firstName: Prisma.FieldRef<"Participant", 'String'>
  readonly lastName: Prisma.FieldRef<"Participant", 'String'>
  readonly dateOfBirth: Prisma.FieldRef<"Participant", 'DateTime'>
  readonly gender: Prisma.FieldRef<"Participant", 'String'>
  readonly address: Prisma.FieldRef<"Participant", 'String'>
  readonly ndisNumber: Prisma.FieldRef<"Participant", 'String'>
  readonly planStartDate: Prisma.FieldRef<"Participant", 'DateTime'>
  readonly planEndDate: Prisma.FieldRef<"Participant", 'DateTime'>
  readonly planManagement: Prisma.FieldRef<"Participant", 'String'>
  readonly status: Prisma.FieldRef<"Participant", 'String'>
  readonly createdAt: Prisma.FieldRef<"Participant", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Participant", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Participant findUnique
 */
export type ParticipantFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * Filter, which Participant to fetch.
   */
  where: Prisma.ParticipantWhereUniqueInput
}

/**
 * Participant findUniqueOrThrow
 */
export type ParticipantFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * Filter, which Participant to fetch.
   */
  where: Prisma.ParticipantWhereUniqueInput
}

/**
 * Participant findFirst
 */
export type ParticipantFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * Filter, which Participant to fetch.
   */
  where?: Prisma.ParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participants to fetch.
   */
  orderBy?: Prisma.ParticipantOrderByWithRelationInput | Prisma.ParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Participants.
   */
  cursor?: Prisma.ParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Participants.
   */
  distinct?: Prisma.ParticipantScalarFieldEnum | Prisma.ParticipantScalarFieldEnum[]
}

/**
 * Participant findFirstOrThrow
 */
export type ParticipantFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * Filter, which Participant to fetch.
   */
  where?: Prisma.ParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participants to fetch.
   */
  orderBy?: Prisma.ParticipantOrderByWithRelationInput | Prisma.ParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Participants.
   */
  cursor?: Prisma.ParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participants.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Participants.
   */
  distinct?: Prisma.ParticipantScalarFieldEnum | Prisma.ParticipantScalarFieldEnum[]
}

/**
 * Participant findMany
 */
export type ParticipantFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * Filter, which Participants to fetch.
   */
  where?: Prisma.ParticipantWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participants to fetch.
   */
  orderBy?: Prisma.ParticipantOrderByWithRelationInput | Prisma.ParticipantOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Participants.
   */
  cursor?: Prisma.ParticipantWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participants from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participants.
   */
  skip?: number
  distinct?: Prisma.ParticipantScalarFieldEnum | Prisma.ParticipantScalarFieldEnum[]
}

/**
 * Participant create
 */
export type ParticipantCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * The data needed to create a Participant.
   */
  data: Prisma.XOR<Prisma.ParticipantCreateInput, Prisma.ParticipantUncheckedCreateInput>
}

/**
 * Participant createMany
 */
export type ParticipantCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Participants.
   */
  data: Prisma.ParticipantCreateManyInput | Prisma.ParticipantCreateManyInput[]
}

/**
 * Participant createManyAndReturn
 */
export type ParticipantCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * The data used to create many Participants.
   */
  data: Prisma.ParticipantCreateManyInput | Prisma.ParticipantCreateManyInput[]
}

/**
 * Participant update
 */
export type ParticipantUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * The data needed to update a Participant.
   */
  data: Prisma.XOR<Prisma.ParticipantUpdateInput, Prisma.ParticipantUncheckedUpdateInput>
  /**
   * Choose, which Participant to update.
   */
  where: Prisma.ParticipantWhereUniqueInput
}

/**
 * Participant updateMany
 */
export type ParticipantUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Participants.
   */
  data: Prisma.XOR<Prisma.ParticipantUpdateManyMutationInput, Prisma.ParticipantUncheckedUpdateManyInput>
  /**
   * Filter which Participants to update
   */
  where?: Prisma.ParticipantWhereInput
  /**
   * Limit how many Participants to update.
   */
  limit?: number
}

/**
 * Participant updateManyAndReturn
 */
export type ParticipantUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * The data used to update Participants.
   */
  data: Prisma.XOR<Prisma.ParticipantUpdateManyMutationInput, Prisma.ParticipantUncheckedUpdateManyInput>
  /**
   * Filter which Participants to update
   */
  where?: Prisma.ParticipantWhereInput
  /**
   * Limit how many Participants to update.
   */
  limit?: number
}

/**
 * Participant upsert
 */
export type ParticipantUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * The filter to search for the Participant to update in case it exists.
   */
  where: Prisma.ParticipantWhereUniqueInput
  /**
   * In case the Participant found by the `where` argument doesn't exist, create a new Participant with this data.
   */
  create: Prisma.XOR<Prisma.ParticipantCreateInput, Prisma.ParticipantUncheckedCreateInput>
  /**
   * In case the Participant was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ParticipantUpdateInput, Prisma.ParticipantUncheckedUpdateInput>
}

/**
 * Participant delete
 */
export type ParticipantDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  /**
   * Filter which Participant to delete.
   */
  where: Prisma.ParticipantWhereUniqueInput
}

/**
 * Participant deleteMany
 */
export type ParticipantDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Participants to delete
   */
  where?: Prisma.ParticipantWhereInput
  /**
   * Limit how many Participants to delete.
   */
  limit?: number
}

/**
 * Participant.contacts
 */
export type Participant$contactsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the EmergencyContact
   */
  select?: Prisma.EmergencyContactSelect<ExtArgs> | null
  /**
   * Omit specific fields from the EmergencyContact
   */
  omit?: Prisma.EmergencyContactOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EmergencyContactInclude<ExtArgs> | null
  where?: Prisma.EmergencyContactWhereInput
  orderBy?: Prisma.EmergencyContactOrderByWithRelationInput | Prisma.EmergencyContactOrderByWithRelationInput[]
  cursor?: Prisma.EmergencyContactWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EmergencyContactScalarFieldEnum | Prisma.EmergencyContactScalarFieldEnum[]
}

/**
 * Participant.incidents
 */
export type Participant$incidentsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  where?: Prisma.IncidentWhereInput
  orderBy?: Prisma.IncidentOrderByWithRelationInput | Prisma.IncidentOrderByWithRelationInput[]
  cursor?: Prisma.IncidentWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.IncidentScalarFieldEnum | Prisma.IncidentScalarFieldEnum[]
}

/**
 * Participant.shiftReports
 */
export type Participant$shiftReportsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  where?: Prisma.ShiftReportWhereInput
  orderBy?: Prisma.ShiftReportOrderByWithRelationInput | Prisma.ShiftReportOrderByWithRelationInput[]
  cursor?: Prisma.ShiftReportWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ShiftReportScalarFieldEnum | Prisma.ShiftReportScalarFieldEnum[]
}

/**
 * Participant.risks
 */
export type Participant$risksArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Risk
   */
  select?: Prisma.RiskSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Risk
   */
  omit?: Prisma.RiskOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RiskInclude<ExtArgs> | null
  where?: Prisma.RiskWhereInput
  orderBy?: Prisma.RiskOrderByWithRelationInput | Prisma.RiskOrderByWithRelationInput[]
  cursor?: Prisma.RiskWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RiskScalarFieldEnum | Prisma.RiskScalarFieldEnum[]
}

/**
 * Participant.restrictivePractices
 */
export type Participant$restrictivePracticesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  where?: Prisma.RestrictivePracticeWhereInput
  orderBy?: Prisma.RestrictivePracticeOrderByWithRelationInput | Prisma.RestrictivePracticeOrderByWithRelationInput[]
  cursor?: Prisma.RestrictivePracticeWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RestrictivePracticeScalarFieldEnum | Prisma.RestrictivePracticeScalarFieldEnum[]
}

/**
 * Participant without action
 */
export type ParticipantDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
}
