
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ShiftReport` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ShiftReport
 * 
 */
export type ShiftReportModel = runtime.Types.Result.DefaultSelection<Prisma.$ShiftReportPayload>

export type AggregateShiftReport = {
  _count: ShiftReportCountAggregateOutputType | null
  _min: ShiftReportMinAggregateOutputType | null
  _max: ShiftReportMaxAggregateOutputType | null
}

export type ShiftReportMinAggregateOutputType = {
  id: string | null
  date: Date | null
  shiftType: string | null
  startTime: string | null
  endTime: string | null
  mood: string | null
  medicationAdministered: boolean | null
  notes: string | null
  handoverNotes: string | null
  incidentOccurred: boolean | null
  participantId: string | null
  staffId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ShiftReportMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  shiftType: string | null
  startTime: string | null
  endTime: string | null
  mood: string | null
  medicationAdministered: boolean | null
  notes: string | null
  handoverNotes: string | null
  incidentOccurred: boolean | null
  participantId: string | null
  staffId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ShiftReportCountAggregateOutputType = {
  id: number
  date: number
  shiftType: number
  startTime: number
  endTime: number
  mood: number
  medicationAdministered: number
  notes: number
  handoverNotes: number
  incidentOccurred: number
  participantId: number
  staffId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ShiftReportMinAggregateInputType = {
  id?: true
  date?: true
  shiftType?: true
  startTime?: true
  endTime?: true
  mood?: true
  medicationAdministered?: true
  notes?: true
  handoverNotes?: true
  incidentOccurred?: true
  participantId?: true
  staffId?: true
  createdAt?: true
  updatedAt?: true
}

export type ShiftReportMaxAggregateInputType = {
  id?: true
  date?: true
  shiftType?: true
  startTime?: true
  endTime?: true
  mood?: true
  medicationAdministered?: true
  notes?: true
  handoverNotes?: true
  incidentOccurred?: true
  participantId?: true
  staffId?: true
  createdAt?: true
  updatedAt?: true
}

export type ShiftReportCountAggregateInputType = {
  id?: true
  date?: true
  shiftType?: true
  startTime?: true
  endTime?: true
  mood?: true
  medicationAdministered?: true
  notes?: true
  handoverNotes?: true
  incidentOccurred?: true
  participantId?: true
  staffId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ShiftReportAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShiftReport to aggregate.
   */
  where?: Prisma.ShiftReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShiftReports to fetch.
   */
  orderBy?: Prisma.ShiftReportOrderByWithRelationInput | Prisma.ShiftReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ShiftReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShiftReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShiftReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ShiftReports
  **/
  _count?: true | ShiftReportCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ShiftReportMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ShiftReportMaxAggregateInputType
}

export type GetShiftReportAggregateType<T extends ShiftReportAggregateArgs> = {
      [P in keyof T & keyof AggregateShiftReport]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShiftReport[P]>
    : Prisma.GetScalarType<T[P], AggregateShiftReport[P]>
}




export type ShiftReportGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ShiftReportWhereInput
  orderBy?: Prisma.ShiftReportOrderByWithAggregationInput | Prisma.ShiftReportOrderByWithAggregationInput[]
  by: Prisma.ShiftReportScalarFieldEnum[] | Prisma.ShiftReportScalarFieldEnum
  having?: Prisma.ShiftReportScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShiftReportCountAggregateInputType | true
  _min?: ShiftReportMinAggregateInputType
  _max?: ShiftReportMaxAggregateInputType
}

export type ShiftReportGroupByOutputType = {
  id: string
  date: Date
  shiftType: string
  startTime: string
  endTime: string
  mood: string | null
  medicationAdministered: boolean
  notes: string
  handoverNotes: string | null
  incidentOccurred: boolean
  participantId: string | null
  staffId: string | null
  createdAt: Date
  updatedAt: Date
  _count: ShiftReportCountAggregateOutputType | null
  _min: ShiftReportMinAggregateOutputType | null
  _max: ShiftReportMaxAggregateOutputType | null
}

type GetShiftReportGroupByPayload<T extends ShiftReportGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShiftReportGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ShiftReportGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ShiftReportGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ShiftReportGroupByOutputType[P]>
      }
    >
  >



export type ShiftReportWhereInput = {
  AND?: Prisma.ShiftReportWhereInput | Prisma.ShiftReportWhereInput[]
  OR?: Prisma.ShiftReportWhereInput[]
  NOT?: Prisma.ShiftReportWhereInput | Prisma.ShiftReportWhereInput[]
  id?: Prisma.StringFilter<"ShiftReport"> | string
  date?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  shiftType?: Prisma.StringFilter<"ShiftReport"> | string
  startTime?: Prisma.StringFilter<"ShiftReport"> | string
  endTime?: Prisma.StringFilter<"ShiftReport"> | string
  mood?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  medicationAdministered?: Prisma.BoolFilter<"ShiftReport"> | boolean
  notes?: Prisma.StringFilter<"ShiftReport"> | string
  handoverNotes?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  incidentOccurred?: Prisma.BoolFilter<"ShiftReport"> | boolean
  participantId?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  staffId?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantNullableScalarRelationFilter, Prisma.ParticipantWhereInput> | null
  staff?: Prisma.XOR<Prisma.StaffNullableScalarRelationFilter, Prisma.StaffWhereInput> | null
}

export type ShiftReportOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftType?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  mood?: Prisma.SortOrderInput | Prisma.SortOrder
  medicationAdministered?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  handoverNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  incidentOccurred?: Prisma.SortOrder
  participantId?: Prisma.SortOrderInput | Prisma.SortOrder
  staffId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  participant?: Prisma.ParticipantOrderByWithRelationInput
  staff?: Prisma.StaffOrderByWithRelationInput
}

export type ShiftReportWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ShiftReportWhereInput | Prisma.ShiftReportWhereInput[]
  OR?: Prisma.ShiftReportWhereInput[]
  NOT?: Prisma.ShiftReportWhereInput | Prisma.ShiftReportWhereInput[]
  date?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  shiftType?: Prisma.StringFilter<"ShiftReport"> | string
  startTime?: Prisma.StringFilter<"ShiftReport"> | string
  endTime?: Prisma.StringFilter<"ShiftReport"> | string
  mood?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  medicationAdministered?: Prisma.BoolFilter<"ShiftReport"> | boolean
  notes?: Prisma.StringFilter<"ShiftReport"> | string
  handoverNotes?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  incidentOccurred?: Prisma.BoolFilter<"ShiftReport"> | boolean
  participantId?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  staffId?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantNullableScalarRelationFilter, Prisma.ParticipantWhereInput> | null
  staff?: Prisma.XOR<Prisma.StaffNullableScalarRelationFilter, Prisma.StaffWhereInput> | null
}, "id">

export type ShiftReportOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftType?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  mood?: Prisma.SortOrderInput | Prisma.SortOrder
  medicationAdministered?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  handoverNotes?: Prisma.SortOrderInput | Prisma.SortOrder
  incidentOccurred?: Prisma.SortOrder
  participantId?: Prisma.SortOrderInput | Prisma.SortOrder
  staffId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ShiftReportCountOrderByAggregateInput
  _max?: Prisma.ShiftReportMaxOrderByAggregateInput
  _min?: Prisma.ShiftReportMinOrderByAggregateInput
}

export type ShiftReportScalarWhereWithAggregatesInput = {
  AND?: Prisma.ShiftReportScalarWhereWithAggregatesInput | Prisma.ShiftReportScalarWhereWithAggregatesInput[]
  OR?: Prisma.ShiftReportScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ShiftReportScalarWhereWithAggregatesInput | Prisma.ShiftReportScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ShiftReport"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"ShiftReport"> | Date | string
  shiftType?: Prisma.StringWithAggregatesFilter<"ShiftReport"> | string
  startTime?: Prisma.StringWithAggregatesFilter<"ShiftReport"> | string
  endTime?: Prisma.StringWithAggregatesFilter<"ShiftReport"> | string
  mood?: Prisma.StringNullableWithAggregatesFilter<"ShiftReport"> | string | null
  medicationAdministered?: Prisma.BoolWithAggregatesFilter<"ShiftReport"> | boolean
  notes?: Prisma.StringWithAggregatesFilter<"ShiftReport"> | string
  handoverNotes?: Prisma.StringNullableWithAggregatesFilter<"ShiftReport"> | string | null
  incidentOccurred?: Prisma.BoolWithAggregatesFilter<"ShiftReport"> | boolean
  participantId?: Prisma.StringNullableWithAggregatesFilter<"ShiftReport"> | string | null
  staffId?: Prisma.StringNullableWithAggregatesFilter<"ShiftReport"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"ShiftReport"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"ShiftReport"> | Date | string
}

export type ShiftReportCreateInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  participant?: Prisma.ParticipantCreateNestedOneWithoutShiftReportsInput
  staff?: Prisma.StaffCreateNestedOneWithoutShiftReportsInput
}

export type ShiftReportUncheckedCreateInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  participantId?: string | null
  staffId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShiftReportUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ParticipantUpdateOneWithoutShiftReportsNestedInput
  staff?: Prisma.StaffUpdateOneWithoutShiftReportsNestedInput
}

export type ShiftReportUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShiftReportCreateManyInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  participantId?: string | null
  staffId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShiftReportUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShiftReportUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShiftReportListRelationFilter = {
  every?: Prisma.ShiftReportWhereInput
  some?: Prisma.ShiftReportWhereInput
  none?: Prisma.ShiftReportWhereInput
}

export type ShiftReportOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ShiftReportCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftType?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  mood?: Prisma.SortOrder
  medicationAdministered?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  handoverNotes?: Prisma.SortOrder
  incidentOccurred?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShiftReportMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftType?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  mood?: Prisma.SortOrder
  medicationAdministered?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  handoverNotes?: Prisma.SortOrder
  incidentOccurred?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShiftReportMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftType?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  mood?: Prisma.SortOrder
  medicationAdministered?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  handoverNotes?: Prisma.SortOrder
  incidentOccurred?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ShiftReportCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutParticipantInput, Prisma.ShiftReportUncheckedCreateWithoutParticipantInput> | Prisma.ShiftReportCreateWithoutParticipantInput[] | Prisma.ShiftReportUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutParticipantInput | Prisma.ShiftReportCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ShiftReportCreateManyParticipantInputEnvelope
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
}

export type ShiftReportUncheckedCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutParticipantInput, Prisma.ShiftReportUncheckedCreateWithoutParticipantInput> | Prisma.ShiftReportCreateWithoutParticipantInput[] | Prisma.ShiftReportUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutParticipantInput | Prisma.ShiftReportCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.ShiftReportCreateManyParticipantInputEnvelope
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
}

export type ShiftReportUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutParticipantInput, Prisma.ShiftReportUncheckedCreateWithoutParticipantInput> | Prisma.ShiftReportCreateWithoutParticipantInput[] | Prisma.ShiftReportUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutParticipantInput | Prisma.ShiftReportCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ShiftReportUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ShiftReportUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ShiftReportCreateManyParticipantInputEnvelope
  set?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  disconnect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  delete?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  update?: Prisma.ShiftReportUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ShiftReportUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ShiftReportUpdateManyWithWhereWithoutParticipantInput | Prisma.ShiftReportUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ShiftReportScalarWhereInput | Prisma.ShiftReportScalarWhereInput[]
}

export type ShiftReportUncheckedUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutParticipantInput, Prisma.ShiftReportUncheckedCreateWithoutParticipantInput> | Prisma.ShiftReportCreateWithoutParticipantInput[] | Prisma.ShiftReportUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutParticipantInput | Prisma.ShiftReportCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.ShiftReportUpsertWithWhereUniqueWithoutParticipantInput | Prisma.ShiftReportUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.ShiftReportCreateManyParticipantInputEnvelope
  set?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  disconnect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  delete?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  update?: Prisma.ShiftReportUpdateWithWhereUniqueWithoutParticipantInput | Prisma.ShiftReportUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.ShiftReportUpdateManyWithWhereWithoutParticipantInput | Prisma.ShiftReportUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.ShiftReportScalarWhereInput | Prisma.ShiftReportScalarWhereInput[]
}

export type ShiftReportCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutStaffInput, Prisma.ShiftReportUncheckedCreateWithoutStaffInput> | Prisma.ShiftReportCreateWithoutStaffInput[] | Prisma.ShiftReportUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutStaffInput | Prisma.ShiftReportCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.ShiftReportCreateManyStaffInputEnvelope
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
}

export type ShiftReportUncheckedCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutStaffInput, Prisma.ShiftReportUncheckedCreateWithoutStaffInput> | Prisma.ShiftReportCreateWithoutStaffInput[] | Prisma.ShiftReportUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutStaffInput | Prisma.ShiftReportCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.ShiftReportCreateManyStaffInputEnvelope
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
}

export type ShiftReportUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutStaffInput, Prisma.ShiftReportUncheckedCreateWithoutStaffInput> | Prisma.ShiftReportCreateWithoutStaffInput[] | Prisma.ShiftReportUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutStaffInput | Prisma.ShiftReportCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.ShiftReportUpsertWithWhereUniqueWithoutStaffInput | Prisma.ShiftReportUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.ShiftReportCreateManyStaffInputEnvelope
  set?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  disconnect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  delete?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  update?: Prisma.ShiftReportUpdateWithWhereUniqueWithoutStaffInput | Prisma.ShiftReportUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.ShiftReportUpdateManyWithWhereWithoutStaffInput | Prisma.ShiftReportUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.ShiftReportScalarWhereInput | Prisma.ShiftReportScalarWhereInput[]
}

export type ShiftReportUncheckedUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.ShiftReportCreateWithoutStaffInput, Prisma.ShiftReportUncheckedCreateWithoutStaffInput> | Prisma.ShiftReportCreateWithoutStaffInput[] | Prisma.ShiftReportUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.ShiftReportCreateOrConnectWithoutStaffInput | Prisma.ShiftReportCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.ShiftReportUpsertWithWhereUniqueWithoutStaffInput | Prisma.ShiftReportUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.ShiftReportCreateManyStaffInputEnvelope
  set?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  disconnect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  delete?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  connect?: Prisma.ShiftReportWhereUniqueInput | Prisma.ShiftReportWhereUniqueInput[]
  update?: Prisma.ShiftReportUpdateWithWhereUniqueWithoutStaffInput | Prisma.ShiftReportUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.ShiftReportUpdateManyWithWhereWithoutStaffInput | Prisma.ShiftReportUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.ShiftReportScalarWhereInput | Prisma.ShiftReportScalarWhereInput[]
}

export type ShiftReportCreateWithoutParticipantInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  staff?: Prisma.StaffCreateNestedOneWithoutShiftReportsInput
}

export type ShiftReportUncheckedCreateWithoutParticipantInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  staffId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShiftReportCreateOrConnectWithoutParticipantInput = {
  where: Prisma.ShiftReportWhereUniqueInput
  create: Prisma.XOR<Prisma.ShiftReportCreateWithoutParticipantInput, Prisma.ShiftReportUncheckedCreateWithoutParticipantInput>
}

export type ShiftReportCreateManyParticipantInputEnvelope = {
  data: Prisma.ShiftReportCreateManyParticipantInput | Prisma.ShiftReportCreateManyParticipantInput[]
}

export type ShiftReportUpsertWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ShiftReportWhereUniqueInput
  update: Prisma.XOR<Prisma.ShiftReportUpdateWithoutParticipantInput, Prisma.ShiftReportUncheckedUpdateWithoutParticipantInput>
  create: Prisma.XOR<Prisma.ShiftReportCreateWithoutParticipantInput, Prisma.ShiftReportUncheckedCreateWithoutParticipantInput>
}

export type ShiftReportUpdateWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.ShiftReportWhereUniqueInput
  data: Prisma.XOR<Prisma.ShiftReportUpdateWithoutParticipantInput, Prisma.ShiftReportUncheckedUpdateWithoutParticipantInput>
}

export type ShiftReportUpdateManyWithWhereWithoutParticipantInput = {
  where: Prisma.ShiftReportScalarWhereInput
  data: Prisma.XOR<Prisma.ShiftReportUpdateManyMutationInput, Prisma.ShiftReportUncheckedUpdateManyWithoutParticipantInput>
}

export type ShiftReportScalarWhereInput = {
  AND?: Prisma.ShiftReportScalarWhereInput | Prisma.ShiftReportScalarWhereInput[]
  OR?: Prisma.ShiftReportScalarWhereInput[]
  NOT?: Prisma.ShiftReportScalarWhereInput | Prisma.ShiftReportScalarWhereInput[]
  id?: Prisma.StringFilter<"ShiftReport"> | string
  date?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  shiftType?: Prisma.StringFilter<"ShiftReport"> | string
  startTime?: Prisma.StringFilter<"ShiftReport"> | string
  endTime?: Prisma.StringFilter<"ShiftReport"> | string
  mood?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  medicationAdministered?: Prisma.BoolFilter<"ShiftReport"> | boolean
  notes?: Prisma.StringFilter<"ShiftReport"> | string
  handoverNotes?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  incidentOccurred?: Prisma.BoolFilter<"ShiftReport"> | boolean
  participantId?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  staffId?: Prisma.StringNullableFilter<"ShiftReport"> | string | null
  createdAt?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"ShiftReport"> | Date | string
}

export type ShiftReportCreateWithoutStaffInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  participant?: Prisma.ParticipantCreateNestedOneWithoutShiftReportsInput
}

export type ShiftReportUncheckedCreateWithoutStaffInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  participantId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShiftReportCreateOrConnectWithoutStaffInput = {
  where: Prisma.ShiftReportWhereUniqueInput
  create: Prisma.XOR<Prisma.ShiftReportCreateWithoutStaffInput, Prisma.ShiftReportUncheckedCreateWithoutStaffInput>
}

export type ShiftReportCreateManyStaffInputEnvelope = {
  data: Prisma.ShiftReportCreateManyStaffInput | Prisma.ShiftReportCreateManyStaffInput[]
}

export type ShiftReportUpsertWithWhereUniqueWithoutStaffInput = {
  where: Prisma.ShiftReportWhereUniqueInput
  update: Prisma.XOR<Prisma.ShiftReportUpdateWithoutStaffInput, Prisma.ShiftReportUncheckedUpdateWithoutStaffInput>
  create: Prisma.XOR<Prisma.ShiftReportCreateWithoutStaffInput, Prisma.ShiftReportUncheckedCreateWithoutStaffInput>
}

export type ShiftReportUpdateWithWhereUniqueWithoutStaffInput = {
  where: Prisma.ShiftReportWhereUniqueInput
  data: Prisma.XOR<Prisma.ShiftReportUpdateWithoutStaffInput, Prisma.ShiftReportUncheckedUpdateWithoutStaffInput>
}

export type ShiftReportUpdateManyWithWhereWithoutStaffInput = {
  where: Prisma.ShiftReportScalarWhereInput
  data: Prisma.XOR<Prisma.ShiftReportUpdateManyMutationInput, Prisma.ShiftReportUncheckedUpdateManyWithoutStaffInput>
}

export type ShiftReportCreateManyParticipantInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  staffId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShiftReportUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staff?: Prisma.StaffUpdateOneWithoutShiftReportsNestedInput
}

export type ShiftReportUncheckedUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShiftReportUncheckedUpdateManyWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShiftReportCreateManyStaffInput = {
  id?: string
  date: Date | string
  shiftType: string
  startTime: string
  endTime: string
  mood?: string | null
  medicationAdministered?: boolean
  notes: string
  handoverNotes?: string | null
  incidentOccurred?: boolean
  participantId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ShiftReportUpdateWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ParticipantUpdateOneWithoutShiftReportsNestedInput
}

export type ShiftReportUncheckedUpdateWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ShiftReportUncheckedUpdateManyWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftType?: Prisma.StringFieldUpdateOperationsInput | string
  startTime?: Prisma.StringFieldUpdateOperationsInput | string
  endTime?: Prisma.StringFieldUpdateOperationsInput | string
  mood?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  medicationAdministered?: Prisma.BoolFieldUpdateOperationsInput | boolean
  notes?: Prisma.StringFieldUpdateOperationsInput | string
  handoverNotes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  incidentOccurred?: Prisma.BoolFieldUpdateOperationsInput | boolean
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ShiftReportSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  shiftType?: boolean
  startTime?: boolean
  endTime?: boolean
  mood?: boolean
  medicationAdministered?: boolean
  notes?: boolean
  handoverNotes?: boolean
  incidentOccurred?: boolean
  participantId?: boolean
  staffId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  participant?: boolean | Prisma.ShiftReport$participantArgs<ExtArgs>
  staff?: boolean | Prisma.ShiftReport$staffArgs<ExtArgs>
}, ExtArgs["result"]["shiftReport"]>

export type ShiftReportSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  shiftType?: boolean
  startTime?: boolean
  endTime?: boolean
  mood?: boolean
  medicationAdministered?: boolean
  notes?: boolean
  handoverNotes?: boolean
  incidentOccurred?: boolean
  participantId?: boolean
  staffId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  participant?: boolean | Prisma.ShiftReport$participantArgs<ExtArgs>
  staff?: boolean | Prisma.ShiftReport$staffArgs<ExtArgs>
}, ExtArgs["result"]["shiftReport"]>

export type ShiftReportSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  shiftType?: boolean
  startTime?: boolean
  endTime?: boolean
  mood?: boolean
  medicationAdministered?: boolean
  notes?: boolean
  handoverNotes?: boolean
  incidentOccurred?: boolean
  participantId?: boolean
  staffId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  participant?: boolean | Prisma.ShiftReport$participantArgs<ExtArgs>
  staff?: boolean | Prisma.ShiftReport$staffArgs<ExtArgs>
}, ExtArgs["result"]["shiftReport"]>

export type ShiftReportSelectScalar = {
  id?: boolean
  date?: boolean
  shiftType?: boolean
  startTime?: boolean
  endTime?: boolean
  mood?: boolean
  medicationAdministered?: boolean
  notes?: boolean
  handoverNotes?: boolean
  incidentOccurred?: boolean
  participantId?: boolean
  staffId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ShiftReportOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "shiftType" | "startTime" | "endTime" | "mood" | "medicationAdministered" | "notes" | "handoverNotes" | "incidentOccurred" | "participantId" | "staffId" | "createdAt" | "updatedAt", ExtArgs["result"]["shiftReport"]>
export type ShiftReportInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.ShiftReport$participantArgs<ExtArgs>
  staff?: boolean | Prisma.ShiftReport$staffArgs<ExtArgs>
}
export type ShiftReportIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.ShiftReport$participantArgs<ExtArgs>
  staff?: boolean | Prisma.ShiftReport$staffArgs<ExtArgs>
}
export type ShiftReportIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.ShiftReport$participantArgs<ExtArgs>
  staff?: boolean | Prisma.ShiftReport$staffArgs<ExtArgs>
}

export type $ShiftReportPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ShiftReport"
  objects: {
    participant: Prisma.$ParticipantPayload<ExtArgs> | null
    staff: Prisma.$StaffPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    shiftType: string
    startTime: string
    endTime: string
    mood: string | null
    medicationAdministered: boolean
    notes: string
    handoverNotes: string | null
    incidentOccurred: boolean
    participantId: string | null
    staffId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["shiftReport"]>
  composites: {}
}

export type ShiftReportGetPayload<S extends boolean | null | undefined | ShiftReportDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload, S>

export type ShiftReportCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ShiftReportFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ShiftReportCountAggregateInputType | true
  }

export interface ShiftReportDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ShiftReport'], meta: { name: 'ShiftReport' } }
  /**
   * Find zero or one ShiftReport that matches the filter.
   * @param {ShiftReportFindUniqueArgs} args - Arguments to find a ShiftReport
   * @example
   * // Get one ShiftReport
   * const shiftReport = await prisma.shiftReport.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ShiftReportFindUniqueArgs>(args: Prisma.SelectSubset<T, ShiftReportFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ShiftReport that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ShiftReportFindUniqueOrThrowArgs} args - Arguments to find a ShiftReport
   * @example
   * // Get one ShiftReport
   * const shiftReport = await prisma.shiftReport.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ShiftReportFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ShiftReportFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShiftReport that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShiftReportFindFirstArgs} args - Arguments to find a ShiftReport
   * @example
   * // Get one ShiftReport
   * const shiftReport = await prisma.shiftReport.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ShiftReportFindFirstArgs>(args?: Prisma.SelectSubset<T, ShiftReportFindFirstArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ShiftReport that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShiftReportFindFirstOrThrowArgs} args - Arguments to find a ShiftReport
   * @example
   * // Get one ShiftReport
   * const shiftReport = await prisma.shiftReport.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ShiftReportFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ShiftReportFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ShiftReports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShiftReportFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ShiftReports
   * const shiftReports = await prisma.shiftReport.findMany()
   * 
   * // Get first 10 ShiftReports
   * const shiftReports = await prisma.shiftReport.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const shiftReportWithIdOnly = await prisma.shiftReport.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ShiftReportFindManyArgs>(args?: Prisma.SelectSubset<T, ShiftReportFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ShiftReport.
   * @param {ShiftReportCreateArgs} args - Arguments to create a ShiftReport.
   * @example
   * // Create one ShiftReport
   * const ShiftReport = await prisma.shiftReport.create({
   *   data: {
   *     // ... data to create a ShiftReport
   *   }
   * })
   * 
   */
  create<T extends ShiftReportCreateArgs>(args: Prisma.SelectSubset<T, ShiftReportCreateArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ShiftReports.
   * @param {ShiftReportCreateManyArgs} args - Arguments to create many ShiftReports.
   * @example
   * // Create many ShiftReports
   * const shiftReport = await prisma.shiftReport.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ShiftReportCreateManyArgs>(args?: Prisma.SelectSubset<T, ShiftReportCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ShiftReports and returns the data saved in the database.
   * @param {ShiftReportCreateManyAndReturnArgs} args - Arguments to create many ShiftReports.
   * @example
   * // Create many ShiftReports
   * const shiftReport = await prisma.shiftReport.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ShiftReports and only return the `id`
   * const shiftReportWithIdOnly = await prisma.shiftReport.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ShiftReportCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ShiftReportCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ShiftReport.
   * @param {ShiftReportDeleteArgs} args - Arguments to delete one ShiftReport.
   * @example
   * // Delete one ShiftReport
   * const ShiftReport = await prisma.shiftReport.delete({
   *   where: {
   *     // ... filter to delete one ShiftReport
   *   }
   * })
   * 
   */
  delete<T extends ShiftReportDeleteArgs>(args: Prisma.SelectSubset<T, ShiftReportDeleteArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ShiftReport.
   * @param {ShiftReportUpdateArgs} args - Arguments to update one ShiftReport.
   * @example
   * // Update one ShiftReport
   * const shiftReport = await prisma.shiftReport.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ShiftReportUpdateArgs>(args: Prisma.SelectSubset<T, ShiftReportUpdateArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ShiftReports.
   * @param {ShiftReportDeleteManyArgs} args - Arguments to filter ShiftReports to delete.
   * @example
   * // Delete a few ShiftReports
   * const { count } = await prisma.shiftReport.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ShiftReportDeleteManyArgs>(args?: Prisma.SelectSubset<T, ShiftReportDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShiftReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShiftReportUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ShiftReports
   * const shiftReport = await prisma.shiftReport.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ShiftReportUpdateManyArgs>(args: Prisma.SelectSubset<T, ShiftReportUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ShiftReports and returns the data updated in the database.
   * @param {ShiftReportUpdateManyAndReturnArgs} args - Arguments to update many ShiftReports.
   * @example
   * // Update many ShiftReports
   * const shiftReport = await prisma.shiftReport.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ShiftReports and only return the `id`
   * const shiftReportWithIdOnly = await prisma.shiftReport.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ShiftReportUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ShiftReportUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ShiftReport.
   * @param {ShiftReportUpsertArgs} args - Arguments to update or create a ShiftReport.
   * @example
   * // Update or create a ShiftReport
   * const shiftReport = await prisma.shiftReport.upsert({
   *   create: {
   *     // ... data to create a ShiftReport
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ShiftReport we want to update
   *   }
   * })
   */
  upsert<T extends ShiftReportUpsertArgs>(args: Prisma.SelectSubset<T, ShiftReportUpsertArgs<ExtArgs>>): Prisma.Prisma__ShiftReportClient<runtime.Types.Result.GetResult<Prisma.$ShiftReportPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ShiftReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShiftReportCountArgs} args - Arguments to filter ShiftReports to count.
   * @example
   * // Count the number of ShiftReports
   * const count = await prisma.shiftReport.count({
   *   where: {
   *     // ... the filter for the ShiftReports we want to count
   *   }
   * })
  **/
  count<T extends ShiftReportCountArgs>(
    args?: Prisma.Subset<T, ShiftReportCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShiftReportCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ShiftReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShiftReportAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ShiftReportAggregateArgs>(args: Prisma.Subset<T, ShiftReportAggregateArgs>): Prisma.PrismaPromise<GetShiftReportAggregateType<T>>

  /**
   * Group by ShiftReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShiftReportGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ShiftReportGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ShiftReportGroupByArgs['orderBy'] }
      : { orderBy?: ShiftReportGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ShiftReportGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetShiftReportGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ShiftReport model
 */
readonly fields: ShiftReportFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ShiftReport.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ShiftReportClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  participant<T extends Prisma.ShiftReport$participantArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShiftReport$participantArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  staff<T extends Prisma.ShiftReport$staffArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShiftReport$staffArgs<ExtArgs>>): Prisma.Prisma__StaffClient<runtime.Types.Result.GetResult<Prisma.$StaffPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ShiftReport model
 */
export interface ShiftReportFieldRefs {
  readonly id: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly date: Prisma.FieldRef<"ShiftReport", 'DateTime'>
  readonly shiftType: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly startTime: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly endTime: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly mood: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly medicationAdministered: Prisma.FieldRef<"ShiftReport", 'Boolean'>
  readonly notes: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly handoverNotes: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly incidentOccurred: Prisma.FieldRef<"ShiftReport", 'Boolean'>
  readonly participantId: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly staffId: Prisma.FieldRef<"ShiftReport", 'String'>
  readonly createdAt: Prisma.FieldRef<"ShiftReport", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"ShiftReport", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ShiftReport findUnique
 */
export type ShiftReportFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * Filter, which ShiftReport to fetch.
   */
  where: Prisma.ShiftReportWhereUniqueInput
}

/**
 * ShiftReport findUniqueOrThrow
 */
export type ShiftReportFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * Filter, which ShiftReport to fetch.
   */
  where: Prisma.ShiftReportWhereUniqueInput
}

/**
 * ShiftReport findFirst
 */
export type ShiftReportFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * Filter, which ShiftReport to fetch.
   */
  where?: Prisma.ShiftReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShiftReports to fetch.
   */
  orderBy?: Prisma.ShiftReportOrderByWithRelationInput | Prisma.ShiftReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShiftReports.
   */
  cursor?: Prisma.ShiftReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShiftReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShiftReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShiftReports.
   */
  distinct?: Prisma.ShiftReportScalarFieldEnum | Prisma.ShiftReportScalarFieldEnum[]
}

/**
 * ShiftReport findFirstOrThrow
 */
export type ShiftReportFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * Filter, which ShiftReport to fetch.
   */
  where?: Prisma.ShiftReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShiftReports to fetch.
   */
  orderBy?: Prisma.ShiftReportOrderByWithRelationInput | Prisma.ShiftReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ShiftReports.
   */
  cursor?: Prisma.ShiftReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShiftReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShiftReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ShiftReports.
   */
  distinct?: Prisma.ShiftReportScalarFieldEnum | Prisma.ShiftReportScalarFieldEnum[]
}

/**
 * ShiftReport findMany
 */
export type ShiftReportFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * Filter, which ShiftReports to fetch.
   */
  where?: Prisma.ShiftReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ShiftReports to fetch.
   */
  orderBy?: Prisma.ShiftReportOrderByWithRelationInput | Prisma.ShiftReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ShiftReports.
   */
  cursor?: Prisma.ShiftReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ShiftReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ShiftReports.
   */
  skip?: number
  distinct?: Prisma.ShiftReportScalarFieldEnum | Prisma.ShiftReportScalarFieldEnum[]
}

/**
 * ShiftReport create
 */
export type ShiftReportCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * The data needed to create a ShiftReport.
   */
  data: Prisma.XOR<Prisma.ShiftReportCreateInput, Prisma.ShiftReportUncheckedCreateInput>
}

/**
 * ShiftReport createMany
 */
export type ShiftReportCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ShiftReports.
   */
  data: Prisma.ShiftReportCreateManyInput | Prisma.ShiftReportCreateManyInput[]
}

/**
 * ShiftReport createManyAndReturn
 */
export type ShiftReportCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * The data used to create many ShiftReports.
   */
  data: Prisma.ShiftReportCreateManyInput | Prisma.ShiftReportCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ShiftReport update
 */
export type ShiftReportUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * The data needed to update a ShiftReport.
   */
  data: Prisma.XOR<Prisma.ShiftReportUpdateInput, Prisma.ShiftReportUncheckedUpdateInput>
  /**
   * Choose, which ShiftReport to update.
   */
  where: Prisma.ShiftReportWhereUniqueInput
}

/**
 * ShiftReport updateMany
 */
export type ShiftReportUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ShiftReports.
   */
  data: Prisma.XOR<Prisma.ShiftReportUpdateManyMutationInput, Prisma.ShiftReportUncheckedUpdateManyInput>
  /**
   * Filter which ShiftReports to update
   */
  where?: Prisma.ShiftReportWhereInput
  /**
   * Limit how many ShiftReports to update.
   */
  limit?: number
}

/**
 * ShiftReport updateManyAndReturn
 */
export type ShiftReportUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * The data used to update ShiftReports.
   */
  data: Prisma.XOR<Prisma.ShiftReportUpdateManyMutationInput, Prisma.ShiftReportUncheckedUpdateManyInput>
  /**
   * Filter which ShiftReports to update
   */
  where?: Prisma.ShiftReportWhereInput
  /**
   * Limit how many ShiftReports to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ShiftReport upsert
 */
export type ShiftReportUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * The filter to search for the ShiftReport to update in case it exists.
   */
  where: Prisma.ShiftReportWhereUniqueInput
  /**
   * In case the ShiftReport found by the `where` argument doesn't exist, create a new ShiftReport with this data.
   */
  create: Prisma.XOR<Prisma.ShiftReportCreateInput, Prisma.ShiftReportUncheckedCreateInput>
  /**
   * In case the ShiftReport was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ShiftReportUpdateInput, Prisma.ShiftReportUncheckedUpdateInput>
}

/**
 * ShiftReport delete
 */
export type ShiftReportDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
  /**
   * Filter which ShiftReport to delete.
   */
  where: Prisma.ShiftReportWhereUniqueInput
}

/**
 * ShiftReport deleteMany
 */
export type ShiftReportDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ShiftReports to delete
   */
  where?: Prisma.ShiftReportWhereInput
  /**
   * Limit how many ShiftReports to delete.
   */
  limit?: number
}

/**
 * ShiftReport.participant
 */
export type ShiftReport$participantArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  where?: Prisma.ParticipantWhereInput
}

/**
 * ShiftReport.staff
 */
export type ShiftReport$staffArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Staff
   */
  select?: Prisma.StaffSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Staff
   */
  omit?: Prisma.StaffOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StaffInclude<ExtArgs> | null
  where?: Prisma.StaffWhereInput
}

/**
 * ShiftReport without action
 */
export type ShiftReportDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShiftReport
   */
  select?: Prisma.ShiftReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ShiftReport
   */
  omit?: Prisma.ShiftReportOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ShiftReportInclude<ExtArgs> | null
}
