
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Participant
 * 
 */
export type Participant = Prisma.ParticipantModel
/**
 * Model EmergencyContact
 * 
 */
export type EmergencyContact = Prisma.EmergencyContactModel
/**
 * Model Staff
 * 
 */
export type Staff = Prisma.StaffModel
/**
 * Model Incident
 * 
 */
export type Incident = Prisma.IncidentModel
/**
 * Model ShiftReport
 * 
 */
export type ShiftReport = Prisma.ShiftReportModel
/**
 * Model RestrictivePractice
 * 
 */
export type RestrictivePractice = Prisma.RestrictivePracticeModel
/**
 * Model Risk
 * 
 */
export type Risk = Prisma.RiskModel
/**
 * Model RegulatoryItem
 * 
 */
export type RegulatoryItem = Prisma.RegulatoryItemModel
