
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Incident` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Incident
 * 
 */
export type IncidentModel = runtime.Types.Result.DefaultSelection<Prisma.$IncidentPayload>

export type AggregateIncident = {
  _count: IncidentCountAggregateOutputType | null
  _min: IncidentMinAggregateOutputType | null
  _max: IncidentMaxAggregateOutputType | null
}

export type IncidentMinAggregateOutputType = {
  id: string | null
  date: Date | null
  time: string | null
  location: string | null
  type: string | null
  description: string | null
  immediateAction: string | null
  severity: string | null
  status: string | null
  participantId: string | null
  staffId: string | null
  managerNotified: boolean | null
  restrictivePracticeUsed: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type IncidentMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  time: string | null
  location: string | null
  type: string | null
  description: string | null
  immediateAction: string | null
  severity: string | null
  status: string | null
  participantId: string | null
  staffId: string | null
  managerNotified: boolean | null
  restrictivePracticeUsed: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type IncidentCountAggregateOutputType = {
  id: number
  date: number
  time: number
  location: number
  type: number
  description: number
  immediateAction: number
  severity: number
  status: number
  participantId: number
  staffId: number
  managerNotified: number
  restrictivePracticeUsed: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type IncidentMinAggregateInputType = {
  id?: true
  date?: true
  time?: true
  location?: true
  type?: true
  description?: true
  immediateAction?: true
  severity?: true
  status?: true
  participantId?: true
  staffId?: true
  managerNotified?: true
  restrictivePracticeUsed?: true
  createdAt?: true
  updatedAt?: true
}

export type IncidentMaxAggregateInputType = {
  id?: true
  date?: true
  time?: true
  location?: true
  type?: true
  description?: true
  immediateAction?: true
  severity?: true
  status?: true
  participantId?: true
  staffId?: true
  managerNotified?: true
  restrictivePracticeUsed?: true
  createdAt?: true
  updatedAt?: true
}

export type IncidentCountAggregateInputType = {
  id?: true
  date?: true
  time?: true
  location?: true
  type?: true
  description?: true
  immediateAction?: true
  severity?: true
  status?: true
  participantId?: true
  staffId?: true
  managerNotified?: true
  restrictivePracticeUsed?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type IncidentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Incident to aggregate.
   */
  where?: Prisma.IncidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incidents to fetch.
   */
  orderBy?: Prisma.IncidentOrderByWithRelationInput | Prisma.IncidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.IncidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incidents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Incidents
  **/
  _count?: true | IncidentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: IncidentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: IncidentMaxAggregateInputType
}

export type GetIncidentAggregateType<T extends IncidentAggregateArgs> = {
      [P in keyof T & keyof AggregateIncident]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIncident[P]>
    : Prisma.GetScalarType<T[P], AggregateIncident[P]>
}




export type IncidentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.IncidentWhereInput
  orderBy?: Prisma.IncidentOrderByWithAggregationInput | Prisma.IncidentOrderByWithAggregationInput[]
  by: Prisma.IncidentScalarFieldEnum[] | Prisma.IncidentScalarFieldEnum
  having?: Prisma.IncidentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: IncidentCountAggregateInputType | true
  _min?: IncidentMinAggregateInputType
  _max?: IncidentMaxAggregateInputType
}

export type IncidentGroupByOutputType = {
  id: string
  date: Date
  time: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity: string
  status: string
  participantId: string | null
  staffId: string | null
  managerNotified: boolean
  restrictivePracticeUsed: boolean
  createdAt: Date
  updatedAt: Date
  _count: IncidentCountAggregateOutputType | null
  _min: IncidentMinAggregateOutputType | null
  _max: IncidentMaxAggregateOutputType | null
}

type GetIncidentGroupByPayload<T extends IncidentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<IncidentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof IncidentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], IncidentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], IncidentGroupByOutputType[P]>
      }
    >
  >



export type IncidentWhereInput = {
  AND?: Prisma.IncidentWhereInput | Prisma.IncidentWhereInput[]
  OR?: Prisma.IncidentWhereInput[]
  NOT?: Prisma.IncidentWhereInput | Prisma.IncidentWhereInput[]
  id?: Prisma.StringFilter<"Incident"> | string
  date?: Prisma.DateTimeFilter<"Incident"> | Date | string
  time?: Prisma.StringNullableFilter<"Incident"> | string | null
  location?: Prisma.StringFilter<"Incident"> | string
  type?: Prisma.StringFilter<"Incident"> | string
  description?: Prisma.StringFilter<"Incident"> | string
  immediateAction?: Prisma.StringFilter<"Incident"> | string
  severity?: Prisma.StringFilter<"Incident"> | string
  status?: Prisma.StringFilter<"Incident"> | string
  participantId?: Prisma.StringNullableFilter<"Incident"> | string | null
  staffId?: Prisma.StringNullableFilter<"Incident"> | string | null
  managerNotified?: Prisma.BoolFilter<"Incident"> | boolean
  restrictivePracticeUsed?: Prisma.BoolFilter<"Incident"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Incident"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Incident"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantNullableScalarRelationFilter, Prisma.ParticipantWhereInput> | null
  staff?: Prisma.XOR<Prisma.StaffNullableScalarRelationFilter, Prisma.StaffWhereInput> | null
}

export type IncidentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  immediateAction?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  participantId?: Prisma.SortOrderInput | Prisma.SortOrder
  staffId?: Prisma.SortOrderInput | Prisma.SortOrder
  managerNotified?: Prisma.SortOrder
  restrictivePracticeUsed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  participant?: Prisma.ParticipantOrderByWithRelationInput
  staff?: Prisma.StaffOrderByWithRelationInput
}

export type IncidentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.IncidentWhereInput | Prisma.IncidentWhereInput[]
  OR?: Prisma.IncidentWhereInput[]
  NOT?: Prisma.IncidentWhereInput | Prisma.IncidentWhereInput[]
  date?: Prisma.DateTimeFilter<"Incident"> | Date | string
  time?: Prisma.StringNullableFilter<"Incident"> | string | null
  location?: Prisma.StringFilter<"Incident"> | string
  type?: Prisma.StringFilter<"Incident"> | string
  description?: Prisma.StringFilter<"Incident"> | string
  immediateAction?: Prisma.StringFilter<"Incident"> | string
  severity?: Prisma.StringFilter<"Incident"> | string
  status?: Prisma.StringFilter<"Incident"> | string
  participantId?: Prisma.StringNullableFilter<"Incident"> | string | null
  staffId?: Prisma.StringNullableFilter<"Incident"> | string | null
  managerNotified?: Prisma.BoolFilter<"Incident"> | boolean
  restrictivePracticeUsed?: Prisma.BoolFilter<"Incident"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Incident"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Incident"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantNullableScalarRelationFilter, Prisma.ParticipantWhereInput> | null
  staff?: Prisma.XOR<Prisma.StaffNullableScalarRelationFilter, Prisma.StaffWhereInput> | null
}, "id">

export type IncidentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  immediateAction?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  participantId?: Prisma.SortOrderInput | Prisma.SortOrder
  staffId?: Prisma.SortOrderInput | Prisma.SortOrder
  managerNotified?: Prisma.SortOrder
  restrictivePracticeUsed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.IncidentCountOrderByAggregateInput
  _max?: Prisma.IncidentMaxOrderByAggregateInput
  _min?: Prisma.IncidentMinOrderByAggregateInput
}

export type IncidentScalarWhereWithAggregatesInput = {
  AND?: Prisma.IncidentScalarWhereWithAggregatesInput | Prisma.IncidentScalarWhereWithAggregatesInput[]
  OR?: Prisma.IncidentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.IncidentScalarWhereWithAggregatesInput | Prisma.IncidentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Incident"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"Incident"> | Date | string
  time?: Prisma.StringNullableWithAggregatesFilter<"Incident"> | string | null
  location?: Prisma.StringWithAggregatesFilter<"Incident"> | string
  type?: Prisma.StringWithAggregatesFilter<"Incident"> | string
  description?: Prisma.StringWithAggregatesFilter<"Incident"> | string
  immediateAction?: Prisma.StringWithAggregatesFilter<"Incident"> | string
  severity?: Prisma.StringWithAggregatesFilter<"Incident"> | string
  status?: Prisma.StringWithAggregatesFilter<"Incident"> | string
  participantId?: Prisma.StringNullableWithAggregatesFilter<"Incident"> | string | null
  staffId?: Prisma.StringNullableWithAggregatesFilter<"Incident"> | string | null
  managerNotified?: Prisma.BoolWithAggregatesFilter<"Incident"> | boolean
  restrictivePracticeUsed?: Prisma.BoolWithAggregatesFilter<"Incident"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Incident"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Incident"> | Date | string
}

export type IncidentCreateInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  participant?: Prisma.ParticipantCreateNestedOneWithoutIncidentsInput
  staff?: Prisma.StaffCreateNestedOneWithoutReportsInput
}

export type IncidentUncheckedCreateInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  participantId?: string | null
  staffId?: string | null
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IncidentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ParticipantUpdateOneWithoutIncidentsNestedInput
  staff?: Prisma.StaffUpdateOneWithoutReportsNestedInput
}

export type IncidentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncidentCreateManyInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  participantId?: string | null
  staffId?: string | null
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IncidentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncidentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncidentListRelationFilter = {
  every?: Prisma.IncidentWhereInput
  some?: Prisma.IncidentWhereInput
  none?: Prisma.IncidentWhereInput
}

export type IncidentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type IncidentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  location?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  immediateAction?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  managerNotified?: Prisma.SortOrder
  restrictivePracticeUsed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IncidentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  location?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  immediateAction?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  managerNotified?: Prisma.SortOrder
  restrictivePracticeUsed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IncidentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  time?: Prisma.SortOrder
  location?: Prisma.SortOrder
  type?: Prisma.SortOrder
  description?: Prisma.SortOrder
  immediateAction?: Prisma.SortOrder
  severity?: Prisma.SortOrder
  status?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  staffId?: Prisma.SortOrder
  managerNotified?: Prisma.SortOrder
  restrictivePracticeUsed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type IncidentCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutParticipantInput, Prisma.IncidentUncheckedCreateWithoutParticipantInput> | Prisma.IncidentCreateWithoutParticipantInput[] | Prisma.IncidentUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutParticipantInput | Prisma.IncidentCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.IncidentCreateManyParticipantInputEnvelope
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
}

export type IncidentUncheckedCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutParticipantInput, Prisma.IncidentUncheckedCreateWithoutParticipantInput> | Prisma.IncidentCreateWithoutParticipantInput[] | Prisma.IncidentUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutParticipantInput | Prisma.IncidentCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.IncidentCreateManyParticipantInputEnvelope
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
}

export type IncidentUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutParticipantInput, Prisma.IncidentUncheckedCreateWithoutParticipantInput> | Prisma.IncidentCreateWithoutParticipantInput[] | Prisma.IncidentUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutParticipantInput | Prisma.IncidentCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.IncidentUpsertWithWhereUniqueWithoutParticipantInput | Prisma.IncidentUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.IncidentCreateManyParticipantInputEnvelope
  set?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  disconnect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  delete?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  update?: Prisma.IncidentUpdateWithWhereUniqueWithoutParticipantInput | Prisma.IncidentUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.IncidentUpdateManyWithWhereWithoutParticipantInput | Prisma.IncidentUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.IncidentScalarWhereInput | Prisma.IncidentScalarWhereInput[]
}

export type IncidentUncheckedUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutParticipantInput, Prisma.IncidentUncheckedCreateWithoutParticipantInput> | Prisma.IncidentCreateWithoutParticipantInput[] | Prisma.IncidentUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutParticipantInput | Prisma.IncidentCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.IncidentUpsertWithWhereUniqueWithoutParticipantInput | Prisma.IncidentUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.IncidentCreateManyParticipantInputEnvelope
  set?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  disconnect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  delete?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  update?: Prisma.IncidentUpdateWithWhereUniqueWithoutParticipantInput | Prisma.IncidentUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.IncidentUpdateManyWithWhereWithoutParticipantInput | Prisma.IncidentUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.IncidentScalarWhereInput | Prisma.IncidentScalarWhereInput[]
}

export type IncidentCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutStaffInput, Prisma.IncidentUncheckedCreateWithoutStaffInput> | Prisma.IncidentCreateWithoutStaffInput[] | Prisma.IncidentUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutStaffInput | Prisma.IncidentCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.IncidentCreateManyStaffInputEnvelope
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
}

export type IncidentUncheckedCreateNestedManyWithoutStaffInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutStaffInput, Prisma.IncidentUncheckedCreateWithoutStaffInput> | Prisma.IncidentCreateWithoutStaffInput[] | Prisma.IncidentUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutStaffInput | Prisma.IncidentCreateOrConnectWithoutStaffInput[]
  createMany?: Prisma.IncidentCreateManyStaffInputEnvelope
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
}

export type IncidentUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutStaffInput, Prisma.IncidentUncheckedCreateWithoutStaffInput> | Prisma.IncidentCreateWithoutStaffInput[] | Prisma.IncidentUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutStaffInput | Prisma.IncidentCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.IncidentUpsertWithWhereUniqueWithoutStaffInput | Prisma.IncidentUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.IncidentCreateManyStaffInputEnvelope
  set?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  disconnect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  delete?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  update?: Prisma.IncidentUpdateWithWhereUniqueWithoutStaffInput | Prisma.IncidentUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.IncidentUpdateManyWithWhereWithoutStaffInput | Prisma.IncidentUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.IncidentScalarWhereInput | Prisma.IncidentScalarWhereInput[]
}

export type IncidentUncheckedUpdateManyWithoutStaffNestedInput = {
  create?: Prisma.XOR<Prisma.IncidentCreateWithoutStaffInput, Prisma.IncidentUncheckedCreateWithoutStaffInput> | Prisma.IncidentCreateWithoutStaffInput[] | Prisma.IncidentUncheckedCreateWithoutStaffInput[]
  connectOrCreate?: Prisma.IncidentCreateOrConnectWithoutStaffInput | Prisma.IncidentCreateOrConnectWithoutStaffInput[]
  upsert?: Prisma.IncidentUpsertWithWhereUniqueWithoutStaffInput | Prisma.IncidentUpsertWithWhereUniqueWithoutStaffInput[]
  createMany?: Prisma.IncidentCreateManyStaffInputEnvelope
  set?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  disconnect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  delete?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  connect?: Prisma.IncidentWhereUniqueInput | Prisma.IncidentWhereUniqueInput[]
  update?: Prisma.IncidentUpdateWithWhereUniqueWithoutStaffInput | Prisma.IncidentUpdateWithWhereUniqueWithoutStaffInput[]
  updateMany?: Prisma.IncidentUpdateManyWithWhereWithoutStaffInput | Prisma.IncidentUpdateManyWithWhereWithoutStaffInput[]
  deleteMany?: Prisma.IncidentScalarWhereInput | Prisma.IncidentScalarWhereInput[]
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type IncidentCreateWithoutParticipantInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  staff?: Prisma.StaffCreateNestedOneWithoutReportsInput
}

export type IncidentUncheckedCreateWithoutParticipantInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  staffId?: string | null
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IncidentCreateOrConnectWithoutParticipantInput = {
  where: Prisma.IncidentWhereUniqueInput
  create: Prisma.XOR<Prisma.IncidentCreateWithoutParticipantInput, Prisma.IncidentUncheckedCreateWithoutParticipantInput>
}

export type IncidentCreateManyParticipantInputEnvelope = {
  data: Prisma.IncidentCreateManyParticipantInput | Prisma.IncidentCreateManyParticipantInput[]
}

export type IncidentUpsertWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.IncidentWhereUniqueInput
  update: Prisma.XOR<Prisma.IncidentUpdateWithoutParticipantInput, Prisma.IncidentUncheckedUpdateWithoutParticipantInput>
  create: Prisma.XOR<Prisma.IncidentCreateWithoutParticipantInput, Prisma.IncidentUncheckedCreateWithoutParticipantInput>
}

export type IncidentUpdateWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.IncidentWhereUniqueInput
  data: Prisma.XOR<Prisma.IncidentUpdateWithoutParticipantInput, Prisma.IncidentUncheckedUpdateWithoutParticipantInput>
}

export type IncidentUpdateManyWithWhereWithoutParticipantInput = {
  where: Prisma.IncidentScalarWhereInput
  data: Prisma.XOR<Prisma.IncidentUpdateManyMutationInput, Prisma.IncidentUncheckedUpdateManyWithoutParticipantInput>
}

export type IncidentScalarWhereInput = {
  AND?: Prisma.IncidentScalarWhereInput | Prisma.IncidentScalarWhereInput[]
  OR?: Prisma.IncidentScalarWhereInput[]
  NOT?: Prisma.IncidentScalarWhereInput | Prisma.IncidentScalarWhereInput[]
  id?: Prisma.StringFilter<"Incident"> | string
  date?: Prisma.DateTimeFilter<"Incident"> | Date | string
  time?: Prisma.StringNullableFilter<"Incident"> | string | null
  location?: Prisma.StringFilter<"Incident"> | string
  type?: Prisma.StringFilter<"Incident"> | string
  description?: Prisma.StringFilter<"Incident"> | string
  immediateAction?: Prisma.StringFilter<"Incident"> | string
  severity?: Prisma.StringFilter<"Incident"> | string
  status?: Prisma.StringFilter<"Incident"> | string
  participantId?: Prisma.StringNullableFilter<"Incident"> | string | null
  staffId?: Prisma.StringNullableFilter<"Incident"> | string | null
  managerNotified?: Prisma.BoolFilter<"Incident"> | boolean
  restrictivePracticeUsed?: Prisma.BoolFilter<"Incident"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Incident"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Incident"> | Date | string
}

export type IncidentCreateWithoutStaffInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  participant?: Prisma.ParticipantCreateNestedOneWithoutIncidentsInput
}

export type IncidentUncheckedCreateWithoutStaffInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  participantId?: string | null
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IncidentCreateOrConnectWithoutStaffInput = {
  where: Prisma.IncidentWhereUniqueInput
  create: Prisma.XOR<Prisma.IncidentCreateWithoutStaffInput, Prisma.IncidentUncheckedCreateWithoutStaffInput>
}

export type IncidentCreateManyStaffInputEnvelope = {
  data: Prisma.IncidentCreateManyStaffInput | Prisma.IncidentCreateManyStaffInput[]
}

export type IncidentUpsertWithWhereUniqueWithoutStaffInput = {
  where: Prisma.IncidentWhereUniqueInput
  update: Prisma.XOR<Prisma.IncidentUpdateWithoutStaffInput, Prisma.IncidentUncheckedUpdateWithoutStaffInput>
  create: Prisma.XOR<Prisma.IncidentCreateWithoutStaffInput, Prisma.IncidentUncheckedCreateWithoutStaffInput>
}

export type IncidentUpdateWithWhereUniqueWithoutStaffInput = {
  where: Prisma.IncidentWhereUniqueInput
  data: Prisma.XOR<Prisma.IncidentUpdateWithoutStaffInput, Prisma.IncidentUncheckedUpdateWithoutStaffInput>
}

export type IncidentUpdateManyWithWhereWithoutStaffInput = {
  where: Prisma.IncidentScalarWhereInput
  data: Prisma.XOR<Prisma.IncidentUpdateManyMutationInput, Prisma.IncidentUncheckedUpdateManyWithoutStaffInput>
}

export type IncidentCreateManyParticipantInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  staffId?: string | null
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IncidentUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  staff?: Prisma.StaffUpdateOneWithoutReportsNestedInput
}

export type IncidentUncheckedUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncidentUncheckedUpdateManyWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  staffId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncidentCreateManyStaffInput = {
  id?: string
  date: Date | string
  time?: string | null
  location: string
  type: string
  description: string
  immediateAction: string
  severity?: string
  status?: string
  participantId?: string | null
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type IncidentUpdateWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ParticipantUpdateOneWithoutIncidentsNestedInput
}

export type IncidentUncheckedUpdateWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type IncidentUncheckedUpdateManyWithoutStaffInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  time?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  immediateAction?: Prisma.StringFieldUpdateOperationsInput | string
  severity?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  managerNotified?: Prisma.BoolFieldUpdateOperationsInput | boolean
  restrictivePracticeUsed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type IncidentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  time?: boolean
  location?: boolean
  type?: boolean
  description?: boolean
  immediateAction?: boolean
  severity?: boolean
  status?: boolean
  participantId?: boolean
  staffId?: boolean
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  participant?: boolean | Prisma.Incident$participantArgs<ExtArgs>
  staff?: boolean | Prisma.Incident$staffArgs<ExtArgs>
}, ExtArgs["result"]["incident"]>

export type IncidentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  time?: boolean
  location?: boolean
  type?: boolean
  description?: boolean
  immediateAction?: boolean
  severity?: boolean
  status?: boolean
  participantId?: boolean
  staffId?: boolean
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  participant?: boolean | Prisma.Incident$participantArgs<ExtArgs>
  staff?: boolean | Prisma.Incident$staffArgs<ExtArgs>
}, ExtArgs["result"]["incident"]>

export type IncidentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  time?: boolean
  location?: boolean
  type?: boolean
  description?: boolean
  immediateAction?: boolean
  severity?: boolean
  status?: boolean
  participantId?: boolean
  staffId?: boolean
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  participant?: boolean | Prisma.Incident$participantArgs<ExtArgs>
  staff?: boolean | Prisma.Incident$staffArgs<ExtArgs>
}, ExtArgs["result"]["incident"]>

export type IncidentSelectScalar = {
  id?: boolean
  date?: boolean
  time?: boolean
  location?: boolean
  type?: boolean
  description?: boolean
  immediateAction?: boolean
  severity?: boolean
  status?: boolean
  participantId?: boolean
  staffId?: boolean
  managerNotified?: boolean
  restrictivePracticeUsed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type IncidentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "time" | "location" | "type" | "description" | "immediateAction" | "severity" | "status" | "participantId" | "staffId" | "managerNotified" | "restrictivePracticeUsed" | "createdAt" | "updatedAt", ExtArgs["result"]["incident"]>
export type IncidentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.Incident$participantArgs<ExtArgs>
  staff?: boolean | Prisma.Incident$staffArgs<ExtArgs>
}
export type IncidentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.Incident$participantArgs<ExtArgs>
  staff?: boolean | Prisma.Incident$staffArgs<ExtArgs>
}
export type IncidentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.Incident$participantArgs<ExtArgs>
  staff?: boolean | Prisma.Incident$staffArgs<ExtArgs>
}

export type $IncidentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Incident"
  objects: {
    participant: Prisma.$ParticipantPayload<ExtArgs> | null
    staff: Prisma.$StaffPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    time: string | null
    location: string
    type: string
    description: string
    immediateAction: string
    severity: string
    status: string
    participantId: string | null
    staffId: string | null
    managerNotified: boolean
    restrictivePracticeUsed: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["incident"]>
  composites: {}
}

export type IncidentGetPayload<S extends boolean | null | undefined | IncidentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$IncidentPayload, S>

export type IncidentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<IncidentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: IncidentCountAggregateInputType | true
  }

export interface IncidentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Incident'], meta: { name: 'Incident' } }
  /**
   * Find zero or one Incident that matches the filter.
   * @param {IncidentFindUniqueArgs} args - Arguments to find a Incident
   * @example
   * // Get one Incident
   * const incident = await prisma.incident.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends IncidentFindUniqueArgs>(args: Prisma.SelectSubset<T, IncidentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Incident that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {IncidentFindUniqueOrThrowArgs} args - Arguments to find a Incident
   * @example
   * // Get one Incident
   * const incident = await prisma.incident.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends IncidentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, IncidentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Incident that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncidentFindFirstArgs} args - Arguments to find a Incident
   * @example
   * // Get one Incident
   * const incident = await prisma.incident.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends IncidentFindFirstArgs>(args?: Prisma.SelectSubset<T, IncidentFindFirstArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Incident that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncidentFindFirstOrThrowArgs} args - Arguments to find a Incident
   * @example
   * // Get one Incident
   * const incident = await prisma.incident.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends IncidentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, IncidentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Incidents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncidentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Incidents
   * const incidents = await prisma.incident.findMany()
   * 
   * // Get first 10 Incidents
   * const incidents = await prisma.incident.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const incidentWithIdOnly = await prisma.incident.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends IncidentFindManyArgs>(args?: Prisma.SelectSubset<T, IncidentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Incident.
   * @param {IncidentCreateArgs} args - Arguments to create a Incident.
   * @example
   * // Create one Incident
   * const Incident = await prisma.incident.create({
   *   data: {
   *     // ... data to create a Incident
   *   }
   * })
   * 
   */
  create<T extends IncidentCreateArgs>(args: Prisma.SelectSubset<T, IncidentCreateArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Incidents.
   * @param {IncidentCreateManyArgs} args - Arguments to create many Incidents.
   * @example
   * // Create many Incidents
   * const incident = await prisma.incident.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends IncidentCreateManyArgs>(args?: Prisma.SelectSubset<T, IncidentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Incidents and returns the data saved in the database.
   * @param {IncidentCreateManyAndReturnArgs} args - Arguments to create many Incidents.
   * @example
   * // Create many Incidents
   * const incident = await prisma.incident.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Incidents and only return the `id`
   * const incidentWithIdOnly = await prisma.incident.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends IncidentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, IncidentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Incident.
   * @param {IncidentDeleteArgs} args - Arguments to delete one Incident.
   * @example
   * // Delete one Incident
   * const Incident = await prisma.incident.delete({
   *   where: {
   *     // ... filter to delete one Incident
   *   }
   * })
   * 
   */
  delete<T extends IncidentDeleteArgs>(args: Prisma.SelectSubset<T, IncidentDeleteArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Incident.
   * @param {IncidentUpdateArgs} args - Arguments to update one Incident.
   * @example
   * // Update one Incident
   * const incident = await prisma.incident.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends IncidentUpdateArgs>(args: Prisma.SelectSubset<T, IncidentUpdateArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Incidents.
   * @param {IncidentDeleteManyArgs} args - Arguments to filter Incidents to delete.
   * @example
   * // Delete a few Incidents
   * const { count } = await prisma.incident.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends IncidentDeleteManyArgs>(args?: Prisma.SelectSubset<T, IncidentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Incidents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncidentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Incidents
   * const incident = await prisma.incident.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends IncidentUpdateManyArgs>(args: Prisma.SelectSubset<T, IncidentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Incidents and returns the data updated in the database.
   * @param {IncidentUpdateManyAndReturnArgs} args - Arguments to update many Incidents.
   * @example
   * // Update many Incidents
   * const incident = await prisma.incident.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Incidents and only return the `id`
   * const incidentWithIdOnly = await prisma.incident.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends IncidentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, IncidentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Incident.
   * @param {IncidentUpsertArgs} args - Arguments to update or create a Incident.
   * @example
   * // Update or create a Incident
   * const incident = await prisma.incident.upsert({
   *   create: {
   *     // ... data to create a Incident
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Incident we want to update
   *   }
   * })
   */
  upsert<T extends IncidentUpsertArgs>(args: Prisma.SelectSubset<T, IncidentUpsertArgs<ExtArgs>>): Prisma.Prisma__IncidentClient<runtime.Types.Result.GetResult<Prisma.$IncidentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Incidents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncidentCountArgs} args - Arguments to filter Incidents to count.
   * @example
   * // Count the number of Incidents
   * const count = await prisma.incident.count({
   *   where: {
   *     // ... the filter for the Incidents we want to count
   *   }
   * })
  **/
  count<T extends IncidentCountArgs>(
    args?: Prisma.Subset<T, IncidentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], IncidentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Incident.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncidentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends IncidentAggregateArgs>(args: Prisma.Subset<T, IncidentAggregateArgs>): Prisma.PrismaPromise<GetIncidentAggregateType<T>>

  /**
   * Group by Incident.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {IncidentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends IncidentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: IncidentGroupByArgs['orderBy'] }
      : { orderBy?: IncidentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, IncidentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIncidentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Incident model
 */
readonly fields: IncidentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Incident.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__IncidentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  participant<T extends Prisma.Incident$participantArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Incident$participantArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  staff<T extends Prisma.Incident$staffArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Incident$staffArgs<ExtArgs>>): Prisma.Prisma__StaffClient<runtime.Types.Result.GetResult<Prisma.$StaffPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Incident model
 */
export interface IncidentFieldRefs {
  readonly id: Prisma.FieldRef<"Incident", 'String'>
  readonly date: Prisma.FieldRef<"Incident", 'DateTime'>
  readonly time: Prisma.FieldRef<"Incident", 'String'>
  readonly location: Prisma.FieldRef<"Incident", 'String'>
  readonly type: Prisma.FieldRef<"Incident", 'String'>
  readonly description: Prisma.FieldRef<"Incident", 'String'>
  readonly immediateAction: Prisma.FieldRef<"Incident", 'String'>
  readonly severity: Prisma.FieldRef<"Incident", 'String'>
  readonly status: Prisma.FieldRef<"Incident", 'String'>
  readonly participantId: Prisma.FieldRef<"Incident", 'String'>
  readonly staffId: Prisma.FieldRef<"Incident", 'String'>
  readonly managerNotified: Prisma.FieldRef<"Incident", 'Boolean'>
  readonly restrictivePracticeUsed: Prisma.FieldRef<"Incident", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Incident", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Incident", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Incident findUnique
 */
export type IncidentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * Filter, which Incident to fetch.
   */
  where: Prisma.IncidentWhereUniqueInput
}

/**
 * Incident findUniqueOrThrow
 */
export type IncidentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * Filter, which Incident to fetch.
   */
  where: Prisma.IncidentWhereUniqueInput
}

/**
 * Incident findFirst
 */
export type IncidentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * Filter, which Incident to fetch.
   */
  where?: Prisma.IncidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incidents to fetch.
   */
  orderBy?: Prisma.IncidentOrderByWithRelationInput | Prisma.IncidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Incidents.
   */
  cursor?: Prisma.IncidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incidents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Incidents.
   */
  distinct?: Prisma.IncidentScalarFieldEnum | Prisma.IncidentScalarFieldEnum[]
}

/**
 * Incident findFirstOrThrow
 */
export type IncidentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * Filter, which Incident to fetch.
   */
  where?: Prisma.IncidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incidents to fetch.
   */
  orderBy?: Prisma.IncidentOrderByWithRelationInput | Prisma.IncidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Incidents.
   */
  cursor?: Prisma.IncidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incidents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Incidents.
   */
  distinct?: Prisma.IncidentScalarFieldEnum | Prisma.IncidentScalarFieldEnum[]
}

/**
 * Incident findMany
 */
export type IncidentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * Filter, which Incidents to fetch.
   */
  where?: Prisma.IncidentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Incidents to fetch.
   */
  orderBy?: Prisma.IncidentOrderByWithRelationInput | Prisma.IncidentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Incidents.
   */
  cursor?: Prisma.IncidentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Incidents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Incidents.
   */
  skip?: number
  distinct?: Prisma.IncidentScalarFieldEnum | Prisma.IncidentScalarFieldEnum[]
}

/**
 * Incident create
 */
export type IncidentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * The data needed to create a Incident.
   */
  data: Prisma.XOR<Prisma.IncidentCreateInput, Prisma.IncidentUncheckedCreateInput>
}

/**
 * Incident createMany
 */
export type IncidentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Incidents.
   */
  data: Prisma.IncidentCreateManyInput | Prisma.IncidentCreateManyInput[]
}

/**
 * Incident createManyAndReturn
 */
export type IncidentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * The data used to create many Incidents.
   */
  data: Prisma.IncidentCreateManyInput | Prisma.IncidentCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Incident update
 */
export type IncidentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * The data needed to update a Incident.
   */
  data: Prisma.XOR<Prisma.IncidentUpdateInput, Prisma.IncidentUncheckedUpdateInput>
  /**
   * Choose, which Incident to update.
   */
  where: Prisma.IncidentWhereUniqueInput
}

/**
 * Incident updateMany
 */
export type IncidentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Incidents.
   */
  data: Prisma.XOR<Prisma.IncidentUpdateManyMutationInput, Prisma.IncidentUncheckedUpdateManyInput>
  /**
   * Filter which Incidents to update
   */
  where?: Prisma.IncidentWhereInput
  /**
   * Limit how many Incidents to update.
   */
  limit?: number
}

/**
 * Incident updateManyAndReturn
 */
export type IncidentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * The data used to update Incidents.
   */
  data: Prisma.XOR<Prisma.IncidentUpdateManyMutationInput, Prisma.IncidentUncheckedUpdateManyInput>
  /**
   * Filter which Incidents to update
   */
  where?: Prisma.IncidentWhereInput
  /**
   * Limit how many Incidents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Incident upsert
 */
export type IncidentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * The filter to search for the Incident to update in case it exists.
   */
  where: Prisma.IncidentWhereUniqueInput
  /**
   * In case the Incident found by the `where` argument doesn't exist, create a new Incident with this data.
   */
  create: Prisma.XOR<Prisma.IncidentCreateInput, Prisma.IncidentUncheckedCreateInput>
  /**
   * In case the Incident was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.IncidentUpdateInput, Prisma.IncidentUncheckedUpdateInput>
}

/**
 * Incident delete
 */
export type IncidentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
  /**
   * Filter which Incident to delete.
   */
  where: Prisma.IncidentWhereUniqueInput
}

/**
 * Incident deleteMany
 */
export type IncidentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Incidents to delete
   */
  where?: Prisma.IncidentWhereInput
  /**
   * Limit how many Incidents to delete.
   */
  limit?: number
}

/**
 * Incident.participant
 */
export type Incident$participantArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participant
   */
  select?: Prisma.ParticipantSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participant
   */
  omit?: Prisma.ParticipantOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipantInclude<ExtArgs> | null
  where?: Prisma.ParticipantWhereInput
}

/**
 * Incident.staff
 */
export type Incident$staffArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Staff
   */
  select?: Prisma.StaffSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Staff
   */
  omit?: Prisma.StaffOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.StaffInclude<ExtArgs> | null
  where?: Prisma.StaffWhereInput
}

/**
 * Incident without action
 */
export type IncidentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Incident
   */
  select?: Prisma.IncidentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Incident
   */
  omit?: Prisma.IncidentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.IncidentInclude<ExtArgs> | null
}
