
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RegulatoryItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RegulatoryItem
 * 
 */
export type RegulatoryItemModel = runtime.Types.Result.DefaultSelection<Prisma.$RegulatoryItemPayload>

export type AggregateRegulatoryItem = {
  _count: RegulatoryItemCountAggregateOutputType | null
  _min: RegulatoryItemMinAggregateOutputType | null
  _max: RegulatoryItemMaxAggregateOutputType | null
}

export type RegulatoryItemMinAggregateOutputType = {
  id: string | null
  standard: string | null
  requirement: string | null
  status: string | null
  lastAudit: Date | null
}

export type RegulatoryItemMaxAggregateOutputType = {
  id: string | null
  standard: string | null
  requirement: string | null
  status: string | null
  lastAudit: Date | null
}

export type RegulatoryItemCountAggregateOutputType = {
  id: number
  standard: number
  requirement: number
  status: number
  lastAudit: number
  _all: number
}


export type RegulatoryItemMinAggregateInputType = {
  id?: true
  standard?: true
  requirement?: true
  status?: true
  lastAudit?: true
}

export type RegulatoryItemMaxAggregateInputType = {
  id?: true
  standard?: true
  requirement?: true
  status?: true
  lastAudit?: true
}

export type RegulatoryItemCountAggregateInputType = {
  id?: true
  standard?: true
  requirement?: true
  status?: true
  lastAudit?: true
  _all?: true
}

export type RegulatoryItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RegulatoryItem to aggregate.
   */
  where?: Prisma.RegulatoryItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegulatoryItems to fetch.
   */
  orderBy?: Prisma.RegulatoryItemOrderByWithRelationInput | Prisma.RegulatoryItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RegulatoryItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegulatoryItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegulatoryItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RegulatoryItems
  **/
  _count?: true | RegulatoryItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RegulatoryItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RegulatoryItemMaxAggregateInputType
}

export type GetRegulatoryItemAggregateType<T extends RegulatoryItemAggregateArgs> = {
      [P in keyof T & keyof AggregateRegulatoryItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRegulatoryItem[P]>
    : Prisma.GetScalarType<T[P], AggregateRegulatoryItem[P]>
}




export type RegulatoryItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegulatoryItemWhereInput
  orderBy?: Prisma.RegulatoryItemOrderByWithAggregationInput | Prisma.RegulatoryItemOrderByWithAggregationInput[]
  by: Prisma.RegulatoryItemScalarFieldEnum[] | Prisma.RegulatoryItemScalarFieldEnum
  having?: Prisma.RegulatoryItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RegulatoryItemCountAggregateInputType | true
  _min?: RegulatoryItemMinAggregateInputType
  _max?: RegulatoryItemMaxAggregateInputType
}

export type RegulatoryItemGroupByOutputType = {
  id: string
  standard: string
  requirement: string
  status: string
  lastAudit: Date | null
  _count: RegulatoryItemCountAggregateOutputType | null
  _min: RegulatoryItemMinAggregateOutputType | null
  _max: RegulatoryItemMaxAggregateOutputType | null
}

type GetRegulatoryItemGroupByPayload<T extends RegulatoryItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RegulatoryItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RegulatoryItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RegulatoryItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RegulatoryItemGroupByOutputType[P]>
      }
    >
  >



export type RegulatoryItemWhereInput = {
  AND?: Prisma.RegulatoryItemWhereInput | Prisma.RegulatoryItemWhereInput[]
  OR?: Prisma.RegulatoryItemWhereInput[]
  NOT?: Prisma.RegulatoryItemWhereInput | Prisma.RegulatoryItemWhereInput[]
  id?: Prisma.StringFilter<"RegulatoryItem"> | string
  standard?: Prisma.StringFilter<"RegulatoryItem"> | string
  requirement?: Prisma.StringFilter<"RegulatoryItem"> | string
  status?: Prisma.StringFilter<"RegulatoryItem"> | string
  lastAudit?: Prisma.DateTimeNullableFilter<"RegulatoryItem"> | Date | string | null
}

export type RegulatoryItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  standard?: Prisma.SortOrder
  requirement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lastAudit?: Prisma.SortOrderInput | Prisma.SortOrder
}

export type RegulatoryItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RegulatoryItemWhereInput | Prisma.RegulatoryItemWhereInput[]
  OR?: Prisma.RegulatoryItemWhereInput[]
  NOT?: Prisma.RegulatoryItemWhereInput | Prisma.RegulatoryItemWhereInput[]
  standard?: Prisma.StringFilter<"RegulatoryItem"> | string
  requirement?: Prisma.StringFilter<"RegulatoryItem"> | string
  status?: Prisma.StringFilter<"RegulatoryItem"> | string
  lastAudit?: Prisma.DateTimeNullableFilter<"RegulatoryItem"> | Date | string | null
}, "id">

export type RegulatoryItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  standard?: Prisma.SortOrder
  requirement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lastAudit?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.RegulatoryItemCountOrderByAggregateInput
  _max?: Prisma.RegulatoryItemMaxOrderByAggregateInput
  _min?: Prisma.RegulatoryItemMinOrderByAggregateInput
}

export type RegulatoryItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.RegulatoryItemScalarWhereWithAggregatesInput | Prisma.RegulatoryItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.RegulatoryItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RegulatoryItemScalarWhereWithAggregatesInput | Prisma.RegulatoryItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RegulatoryItem"> | string
  standard?: Prisma.StringWithAggregatesFilter<"RegulatoryItem"> | string
  requirement?: Prisma.StringWithAggregatesFilter<"RegulatoryItem"> | string
  status?: Prisma.StringWithAggregatesFilter<"RegulatoryItem"> | string
  lastAudit?: Prisma.DateTimeNullableWithAggregatesFilter<"RegulatoryItem"> | Date | string | null
}

export type RegulatoryItemCreateInput = {
  id?: string
  standard: string
  requirement: string
  status: string
  lastAudit?: Date | string | null
}

export type RegulatoryItemUncheckedCreateInput = {
  id?: string
  standard: string
  requirement: string
  status: string
  lastAudit?: Date | string | null
}

export type RegulatoryItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  standard?: Prisma.StringFieldUpdateOperationsInput | string
  requirement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  lastAudit?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegulatoryItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  standard?: Prisma.StringFieldUpdateOperationsInput | string
  requirement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  lastAudit?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegulatoryItemCreateManyInput = {
  id?: string
  standard: string
  requirement: string
  status: string
  lastAudit?: Date | string | null
}

export type RegulatoryItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  standard?: Prisma.StringFieldUpdateOperationsInput | string
  requirement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  lastAudit?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegulatoryItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  standard?: Prisma.StringFieldUpdateOperationsInput | string
  requirement?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  lastAudit?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type RegulatoryItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  standard?: Prisma.SortOrder
  requirement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lastAudit?: Prisma.SortOrder
}

export type RegulatoryItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  standard?: Prisma.SortOrder
  requirement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lastAudit?: Prisma.SortOrder
}

export type RegulatoryItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  standard?: Prisma.SortOrder
  requirement?: Prisma.SortOrder
  status?: Prisma.SortOrder
  lastAudit?: Prisma.SortOrder
}



export type RegulatoryItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  standard?: boolean
  requirement?: boolean
  status?: boolean
  lastAudit?: boolean
}, ExtArgs["result"]["regulatoryItem"]>

export type RegulatoryItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  standard?: boolean
  requirement?: boolean
  status?: boolean
  lastAudit?: boolean
}, ExtArgs["result"]["regulatoryItem"]>

export type RegulatoryItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  standard?: boolean
  requirement?: boolean
  status?: boolean
  lastAudit?: boolean
}, ExtArgs["result"]["regulatoryItem"]>

export type RegulatoryItemSelectScalar = {
  id?: boolean
  standard?: boolean
  requirement?: boolean
  status?: boolean
  lastAudit?: boolean
}

export type RegulatoryItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "standard" | "requirement" | "status" | "lastAudit", ExtArgs["result"]["regulatoryItem"]>

export type $RegulatoryItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RegulatoryItem"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    standard: string
    requirement: string
    status: string
    lastAudit: Date | null
  }, ExtArgs["result"]["regulatoryItem"]>
  composites: {}
}

export type RegulatoryItemGetPayload<S extends boolean | null | undefined | RegulatoryItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload, S>

export type RegulatoryItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RegulatoryItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RegulatoryItemCountAggregateInputType | true
  }

export interface RegulatoryItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RegulatoryItem'], meta: { name: 'RegulatoryItem' } }
  /**
   * Find zero or one RegulatoryItem that matches the filter.
   * @param {RegulatoryItemFindUniqueArgs} args - Arguments to find a RegulatoryItem
   * @example
   * // Get one RegulatoryItem
   * const regulatoryItem = await prisma.regulatoryItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RegulatoryItemFindUniqueArgs>(args: Prisma.SelectSubset<T, RegulatoryItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RegulatoryItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RegulatoryItemFindUniqueOrThrowArgs} args - Arguments to find a RegulatoryItem
   * @example
   * // Get one RegulatoryItem
   * const regulatoryItem = await prisma.regulatoryItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RegulatoryItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RegulatoryItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RegulatoryItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegulatoryItemFindFirstArgs} args - Arguments to find a RegulatoryItem
   * @example
   * // Get one RegulatoryItem
   * const regulatoryItem = await prisma.regulatoryItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RegulatoryItemFindFirstArgs>(args?: Prisma.SelectSubset<T, RegulatoryItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RegulatoryItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegulatoryItemFindFirstOrThrowArgs} args - Arguments to find a RegulatoryItem
   * @example
   * // Get one RegulatoryItem
   * const regulatoryItem = await prisma.regulatoryItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RegulatoryItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RegulatoryItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RegulatoryItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegulatoryItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RegulatoryItems
   * const regulatoryItems = await prisma.regulatoryItem.findMany()
   * 
   * // Get first 10 RegulatoryItems
   * const regulatoryItems = await prisma.regulatoryItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const regulatoryItemWithIdOnly = await prisma.regulatoryItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RegulatoryItemFindManyArgs>(args?: Prisma.SelectSubset<T, RegulatoryItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RegulatoryItem.
   * @param {RegulatoryItemCreateArgs} args - Arguments to create a RegulatoryItem.
   * @example
   * // Create one RegulatoryItem
   * const RegulatoryItem = await prisma.regulatoryItem.create({
   *   data: {
   *     // ... data to create a RegulatoryItem
   *   }
   * })
   * 
   */
  create<T extends RegulatoryItemCreateArgs>(args: Prisma.SelectSubset<T, RegulatoryItemCreateArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RegulatoryItems.
   * @param {RegulatoryItemCreateManyArgs} args - Arguments to create many RegulatoryItems.
   * @example
   * // Create many RegulatoryItems
   * const regulatoryItem = await prisma.regulatoryItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RegulatoryItemCreateManyArgs>(args?: Prisma.SelectSubset<T, RegulatoryItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RegulatoryItems and returns the data saved in the database.
   * @param {RegulatoryItemCreateManyAndReturnArgs} args - Arguments to create many RegulatoryItems.
   * @example
   * // Create many RegulatoryItems
   * const regulatoryItem = await prisma.regulatoryItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RegulatoryItems and only return the `id`
   * const regulatoryItemWithIdOnly = await prisma.regulatoryItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RegulatoryItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RegulatoryItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RegulatoryItem.
   * @param {RegulatoryItemDeleteArgs} args - Arguments to delete one RegulatoryItem.
   * @example
   * // Delete one RegulatoryItem
   * const RegulatoryItem = await prisma.regulatoryItem.delete({
   *   where: {
   *     // ... filter to delete one RegulatoryItem
   *   }
   * })
   * 
   */
  delete<T extends RegulatoryItemDeleteArgs>(args: Prisma.SelectSubset<T, RegulatoryItemDeleteArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RegulatoryItem.
   * @param {RegulatoryItemUpdateArgs} args - Arguments to update one RegulatoryItem.
   * @example
   * // Update one RegulatoryItem
   * const regulatoryItem = await prisma.regulatoryItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RegulatoryItemUpdateArgs>(args: Prisma.SelectSubset<T, RegulatoryItemUpdateArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RegulatoryItems.
   * @param {RegulatoryItemDeleteManyArgs} args - Arguments to filter RegulatoryItems to delete.
   * @example
   * // Delete a few RegulatoryItems
   * const { count } = await prisma.regulatoryItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RegulatoryItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, RegulatoryItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RegulatoryItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegulatoryItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RegulatoryItems
   * const regulatoryItem = await prisma.regulatoryItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RegulatoryItemUpdateManyArgs>(args: Prisma.SelectSubset<T, RegulatoryItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RegulatoryItems and returns the data updated in the database.
   * @param {RegulatoryItemUpdateManyAndReturnArgs} args - Arguments to update many RegulatoryItems.
   * @example
   * // Update many RegulatoryItems
   * const regulatoryItem = await prisma.regulatoryItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RegulatoryItems and only return the `id`
   * const regulatoryItemWithIdOnly = await prisma.regulatoryItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RegulatoryItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RegulatoryItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RegulatoryItem.
   * @param {RegulatoryItemUpsertArgs} args - Arguments to update or create a RegulatoryItem.
   * @example
   * // Update or create a RegulatoryItem
   * const regulatoryItem = await prisma.regulatoryItem.upsert({
   *   create: {
   *     // ... data to create a RegulatoryItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RegulatoryItem we want to update
   *   }
   * })
   */
  upsert<T extends RegulatoryItemUpsertArgs>(args: Prisma.SelectSubset<T, RegulatoryItemUpsertArgs<ExtArgs>>): Prisma.Prisma__RegulatoryItemClient<runtime.Types.Result.GetResult<Prisma.$RegulatoryItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RegulatoryItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegulatoryItemCountArgs} args - Arguments to filter RegulatoryItems to count.
   * @example
   * // Count the number of RegulatoryItems
   * const count = await prisma.regulatoryItem.count({
   *   where: {
   *     // ... the filter for the RegulatoryItems we want to count
   *   }
   * })
  **/
  count<T extends RegulatoryItemCountArgs>(
    args?: Prisma.Subset<T, RegulatoryItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RegulatoryItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RegulatoryItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegulatoryItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RegulatoryItemAggregateArgs>(args: Prisma.Subset<T, RegulatoryItemAggregateArgs>): Prisma.PrismaPromise<GetRegulatoryItemAggregateType<T>>

  /**
   * Group by RegulatoryItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegulatoryItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RegulatoryItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RegulatoryItemGroupByArgs['orderBy'] }
      : { orderBy?: RegulatoryItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RegulatoryItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRegulatoryItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RegulatoryItem model
 */
readonly fields: RegulatoryItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RegulatoryItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RegulatoryItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RegulatoryItem model
 */
export interface RegulatoryItemFieldRefs {
  readonly id: Prisma.FieldRef<"RegulatoryItem", 'String'>
  readonly standard: Prisma.FieldRef<"RegulatoryItem", 'String'>
  readonly requirement: Prisma.FieldRef<"RegulatoryItem", 'String'>
  readonly status: Prisma.FieldRef<"RegulatoryItem", 'String'>
  readonly lastAudit: Prisma.FieldRef<"RegulatoryItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RegulatoryItem findUnique
 */
export type RegulatoryItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * Filter, which RegulatoryItem to fetch.
   */
  where: Prisma.RegulatoryItemWhereUniqueInput
}

/**
 * RegulatoryItem findUniqueOrThrow
 */
export type RegulatoryItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * Filter, which RegulatoryItem to fetch.
   */
  where: Prisma.RegulatoryItemWhereUniqueInput
}

/**
 * RegulatoryItem findFirst
 */
export type RegulatoryItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * Filter, which RegulatoryItem to fetch.
   */
  where?: Prisma.RegulatoryItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegulatoryItems to fetch.
   */
  orderBy?: Prisma.RegulatoryItemOrderByWithRelationInput | Prisma.RegulatoryItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RegulatoryItems.
   */
  cursor?: Prisma.RegulatoryItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegulatoryItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegulatoryItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RegulatoryItems.
   */
  distinct?: Prisma.RegulatoryItemScalarFieldEnum | Prisma.RegulatoryItemScalarFieldEnum[]
}

/**
 * RegulatoryItem findFirstOrThrow
 */
export type RegulatoryItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * Filter, which RegulatoryItem to fetch.
   */
  where?: Prisma.RegulatoryItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegulatoryItems to fetch.
   */
  orderBy?: Prisma.RegulatoryItemOrderByWithRelationInput | Prisma.RegulatoryItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RegulatoryItems.
   */
  cursor?: Prisma.RegulatoryItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegulatoryItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegulatoryItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RegulatoryItems.
   */
  distinct?: Prisma.RegulatoryItemScalarFieldEnum | Prisma.RegulatoryItemScalarFieldEnum[]
}

/**
 * RegulatoryItem findMany
 */
export type RegulatoryItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * Filter, which RegulatoryItems to fetch.
   */
  where?: Prisma.RegulatoryItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RegulatoryItems to fetch.
   */
  orderBy?: Prisma.RegulatoryItemOrderByWithRelationInput | Prisma.RegulatoryItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RegulatoryItems.
   */
  cursor?: Prisma.RegulatoryItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RegulatoryItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RegulatoryItems.
   */
  skip?: number
  distinct?: Prisma.RegulatoryItemScalarFieldEnum | Prisma.RegulatoryItemScalarFieldEnum[]
}

/**
 * RegulatoryItem create
 */
export type RegulatoryItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * The data needed to create a RegulatoryItem.
   */
  data: Prisma.XOR<Prisma.RegulatoryItemCreateInput, Prisma.RegulatoryItemUncheckedCreateInput>
}

/**
 * RegulatoryItem createMany
 */
export type RegulatoryItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RegulatoryItems.
   */
  data: Prisma.RegulatoryItemCreateManyInput | Prisma.RegulatoryItemCreateManyInput[]
}

/**
 * RegulatoryItem createManyAndReturn
 */
export type RegulatoryItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * The data used to create many RegulatoryItems.
   */
  data: Prisma.RegulatoryItemCreateManyInput | Prisma.RegulatoryItemCreateManyInput[]
}

/**
 * RegulatoryItem update
 */
export type RegulatoryItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * The data needed to update a RegulatoryItem.
   */
  data: Prisma.XOR<Prisma.RegulatoryItemUpdateInput, Prisma.RegulatoryItemUncheckedUpdateInput>
  /**
   * Choose, which RegulatoryItem to update.
   */
  where: Prisma.RegulatoryItemWhereUniqueInput
}

/**
 * RegulatoryItem updateMany
 */
export type RegulatoryItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RegulatoryItems.
   */
  data: Prisma.XOR<Prisma.RegulatoryItemUpdateManyMutationInput, Prisma.RegulatoryItemUncheckedUpdateManyInput>
  /**
   * Filter which RegulatoryItems to update
   */
  where?: Prisma.RegulatoryItemWhereInput
  /**
   * Limit how many RegulatoryItems to update.
   */
  limit?: number
}

/**
 * RegulatoryItem updateManyAndReturn
 */
export type RegulatoryItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * The data used to update RegulatoryItems.
   */
  data: Prisma.XOR<Prisma.RegulatoryItemUpdateManyMutationInput, Prisma.RegulatoryItemUncheckedUpdateManyInput>
  /**
   * Filter which RegulatoryItems to update
   */
  where?: Prisma.RegulatoryItemWhereInput
  /**
   * Limit how many RegulatoryItems to update.
   */
  limit?: number
}

/**
 * RegulatoryItem upsert
 */
export type RegulatoryItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * The filter to search for the RegulatoryItem to update in case it exists.
   */
  where: Prisma.RegulatoryItemWhereUniqueInput
  /**
   * In case the RegulatoryItem found by the `where` argument doesn't exist, create a new RegulatoryItem with this data.
   */
  create: Prisma.XOR<Prisma.RegulatoryItemCreateInput, Prisma.RegulatoryItemUncheckedCreateInput>
  /**
   * In case the RegulatoryItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RegulatoryItemUpdateInput, Prisma.RegulatoryItemUncheckedUpdateInput>
}

/**
 * RegulatoryItem delete
 */
export type RegulatoryItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
  /**
   * Filter which RegulatoryItem to delete.
   */
  where: Prisma.RegulatoryItemWhereUniqueInput
}

/**
 * RegulatoryItem deleteMany
 */
export type RegulatoryItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RegulatoryItems to delete
   */
  where?: Prisma.RegulatoryItemWhereInput
  /**
   * Limit how many RegulatoryItems to delete.
   */
  limit?: number
}

/**
 * RegulatoryItem without action
 */
export type RegulatoryItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegulatoryItem
   */
  select?: Prisma.RegulatoryItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RegulatoryItem
   */
  omit?: Prisma.RegulatoryItemOmit<ExtArgs> | null
}
