
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RestrictivePractice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RestrictivePractice
 * 
 */
export type RestrictivePracticeModel = runtime.Types.Result.DefaultSelection<Prisma.$RestrictivePracticePayload>

export type AggregateRestrictivePractice = {
  _count: RestrictivePracticeCountAggregateOutputType | null
  _min: RestrictivePracticeMinAggregateOutputType | null
  _max: RestrictivePracticeMaxAggregateOutputType | null
}

export type RestrictivePracticeMinAggregateOutputType = {
  id: string | null
  type: string | null
  isAuthorized: boolean | null
  startTime: Date | null
  endTime: Date | null
  reason: string | null
  strategies: string | null
  staffInvolved: string | null
  participantId: string | null
  createdAt: Date | null
}

export type RestrictivePracticeMaxAggregateOutputType = {
  id: string | null
  type: string | null
  isAuthorized: boolean | null
  startTime: Date | null
  endTime: Date | null
  reason: string | null
  strategies: string | null
  staffInvolved: string | null
  participantId: string | null
  createdAt: Date | null
}

export type RestrictivePracticeCountAggregateOutputType = {
  id: number
  type: number
  isAuthorized: number
  startTime: number
  endTime: number
  reason: number
  strategies: number
  staffInvolved: number
  participantId: number
  createdAt: number
  _all: number
}


export type RestrictivePracticeMinAggregateInputType = {
  id?: true
  type?: true
  isAuthorized?: true
  startTime?: true
  endTime?: true
  reason?: true
  strategies?: true
  staffInvolved?: true
  participantId?: true
  createdAt?: true
}

export type RestrictivePracticeMaxAggregateInputType = {
  id?: true
  type?: true
  isAuthorized?: true
  startTime?: true
  endTime?: true
  reason?: true
  strategies?: true
  staffInvolved?: true
  participantId?: true
  createdAt?: true
}

export type RestrictivePracticeCountAggregateInputType = {
  id?: true
  type?: true
  isAuthorized?: true
  startTime?: true
  endTime?: true
  reason?: true
  strategies?: true
  staffInvolved?: true
  participantId?: true
  createdAt?: true
  _all?: true
}

export type RestrictivePracticeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RestrictivePractice to aggregate.
   */
  where?: Prisma.RestrictivePracticeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestrictivePractices to fetch.
   */
  orderBy?: Prisma.RestrictivePracticeOrderByWithRelationInput | Prisma.RestrictivePracticeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RestrictivePracticeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestrictivePractices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestrictivePractices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RestrictivePractices
  **/
  _count?: true | RestrictivePracticeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RestrictivePracticeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RestrictivePracticeMaxAggregateInputType
}

export type GetRestrictivePracticeAggregateType<T extends RestrictivePracticeAggregateArgs> = {
      [P in keyof T & keyof AggregateRestrictivePractice]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRestrictivePractice[P]>
    : Prisma.GetScalarType<T[P], AggregateRestrictivePractice[P]>
}




export type RestrictivePracticeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RestrictivePracticeWhereInput
  orderBy?: Prisma.RestrictivePracticeOrderByWithAggregationInput | Prisma.RestrictivePracticeOrderByWithAggregationInput[]
  by: Prisma.RestrictivePracticeScalarFieldEnum[] | Prisma.RestrictivePracticeScalarFieldEnum
  having?: Prisma.RestrictivePracticeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RestrictivePracticeCountAggregateInputType | true
  _min?: RestrictivePracticeMinAggregateInputType
  _max?: RestrictivePracticeMaxAggregateInputType
}

export type RestrictivePracticeGroupByOutputType = {
  id: string
  type: string
  isAuthorized: boolean
  startTime: Date
  endTime: Date | null
  reason: string
  strategies: string
  staffInvolved: string
  participantId: string
  createdAt: Date
  _count: RestrictivePracticeCountAggregateOutputType | null
  _min: RestrictivePracticeMinAggregateOutputType | null
  _max: RestrictivePracticeMaxAggregateOutputType | null
}

type GetRestrictivePracticeGroupByPayload<T extends RestrictivePracticeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RestrictivePracticeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RestrictivePracticeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RestrictivePracticeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RestrictivePracticeGroupByOutputType[P]>
      }
    >
  >



export type RestrictivePracticeWhereInput = {
  AND?: Prisma.RestrictivePracticeWhereInput | Prisma.RestrictivePracticeWhereInput[]
  OR?: Prisma.RestrictivePracticeWhereInput[]
  NOT?: Prisma.RestrictivePracticeWhereInput | Prisma.RestrictivePracticeWhereInput[]
  id?: Prisma.StringFilter<"RestrictivePractice"> | string
  type?: Prisma.StringFilter<"RestrictivePractice"> | string
  isAuthorized?: Prisma.BoolFilter<"RestrictivePractice"> | boolean
  startTime?: Prisma.DateTimeFilter<"RestrictivePractice"> | Date | string
  endTime?: Prisma.DateTimeNullableFilter<"RestrictivePractice"> | Date | string | null
  reason?: Prisma.StringFilter<"RestrictivePractice"> | string
  strategies?: Prisma.StringFilter<"RestrictivePractice"> | string
  staffInvolved?: Prisma.StringFilter<"RestrictivePractice"> | string
  participantId?: Prisma.StringFilter<"RestrictivePractice"> | string
  createdAt?: Prisma.DateTimeFilter<"RestrictivePractice"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantScalarRelationFilter, Prisma.ParticipantWhereInput>
}

export type RestrictivePracticeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isAuthorized?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrderInput | Prisma.SortOrder
  reason?: Prisma.SortOrder
  strategies?: Prisma.SortOrder
  staffInvolved?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  participant?: Prisma.ParticipantOrderByWithRelationInput
}

export type RestrictivePracticeWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RestrictivePracticeWhereInput | Prisma.RestrictivePracticeWhereInput[]
  OR?: Prisma.RestrictivePracticeWhereInput[]
  NOT?: Prisma.RestrictivePracticeWhereInput | Prisma.RestrictivePracticeWhereInput[]
  type?: Prisma.StringFilter<"RestrictivePractice"> | string
  isAuthorized?: Prisma.BoolFilter<"RestrictivePractice"> | boolean
  startTime?: Prisma.DateTimeFilter<"RestrictivePractice"> | Date | string
  endTime?: Prisma.DateTimeNullableFilter<"RestrictivePractice"> | Date | string | null
  reason?: Prisma.StringFilter<"RestrictivePractice"> | string
  strategies?: Prisma.StringFilter<"RestrictivePractice"> | string
  staffInvolved?: Prisma.StringFilter<"RestrictivePractice"> | string
  participantId?: Prisma.StringFilter<"RestrictivePractice"> | string
  createdAt?: Prisma.DateTimeFilter<"RestrictivePractice"> | Date | string
  participant?: Prisma.XOR<Prisma.ParticipantScalarRelationFilter, Prisma.ParticipantWhereInput>
}, "id">

export type RestrictivePracticeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isAuthorized?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrderInput | Prisma.SortOrder
  reason?: Prisma.SortOrder
  strategies?: Prisma.SortOrder
  staffInvolved?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.RestrictivePracticeCountOrderByAggregateInput
  _max?: Prisma.RestrictivePracticeMaxOrderByAggregateInput
  _min?: Prisma.RestrictivePracticeMinOrderByAggregateInput
}

export type RestrictivePracticeScalarWhereWithAggregatesInput = {
  AND?: Prisma.RestrictivePracticeScalarWhereWithAggregatesInput | Prisma.RestrictivePracticeScalarWhereWithAggregatesInput[]
  OR?: Prisma.RestrictivePracticeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RestrictivePracticeScalarWhereWithAggregatesInput | Prisma.RestrictivePracticeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RestrictivePractice"> | string
  type?: Prisma.StringWithAggregatesFilter<"RestrictivePractice"> | string
  isAuthorized?: Prisma.BoolWithAggregatesFilter<"RestrictivePractice"> | boolean
  startTime?: Prisma.DateTimeWithAggregatesFilter<"RestrictivePractice"> | Date | string
  endTime?: Prisma.DateTimeNullableWithAggregatesFilter<"RestrictivePractice"> | Date | string | null
  reason?: Prisma.StringWithAggregatesFilter<"RestrictivePractice"> | string
  strategies?: Prisma.StringWithAggregatesFilter<"RestrictivePractice"> | string
  staffInvolved?: Prisma.StringWithAggregatesFilter<"RestrictivePractice"> | string
  participantId?: Prisma.StringWithAggregatesFilter<"RestrictivePractice"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RestrictivePractice"> | Date | string
}

export type RestrictivePracticeCreateInput = {
  id?: string
  type: string
  isAuthorized: boolean
  startTime: Date | string
  endTime?: Date | string | null
  reason: string
  strategies: string
  staffInvolved: string
  createdAt?: Date | string
  participant: Prisma.ParticipantCreateNestedOneWithoutRestrictivePracticesInput
}

export type RestrictivePracticeUncheckedCreateInput = {
  id?: string
  type: string
  isAuthorized: boolean
  startTime: Date | string
  endTime?: Date | string | null
  reason: string
  strategies: string
  staffInvolved: string
  participantId: string
  createdAt?: Date | string
}

export type RestrictivePracticeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isAuthorized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  strategies?: Prisma.StringFieldUpdateOperationsInput | string
  staffInvolved?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  participant?: Prisma.ParticipantUpdateOneRequiredWithoutRestrictivePracticesNestedInput
}

export type RestrictivePracticeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isAuthorized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  strategies?: Prisma.StringFieldUpdateOperationsInput | string
  staffInvolved?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestrictivePracticeCreateManyInput = {
  id?: string
  type: string
  isAuthorized: boolean
  startTime: Date | string
  endTime?: Date | string | null
  reason: string
  strategies: string
  staffInvolved: string
  participantId: string
  createdAt?: Date | string
}

export type RestrictivePracticeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isAuthorized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  strategies?: Prisma.StringFieldUpdateOperationsInput | string
  staffInvolved?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestrictivePracticeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isAuthorized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  strategies?: Prisma.StringFieldUpdateOperationsInput | string
  staffInvolved?: Prisma.StringFieldUpdateOperationsInput | string
  participantId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestrictivePracticeListRelationFilter = {
  every?: Prisma.RestrictivePracticeWhereInput
  some?: Prisma.RestrictivePracticeWhereInput
  none?: Prisma.RestrictivePracticeWhereInput
}

export type RestrictivePracticeOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RestrictivePracticeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isAuthorized?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  strategies?: Prisma.SortOrder
  staffInvolved?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RestrictivePracticeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isAuthorized?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  strategies?: Prisma.SortOrder
  staffInvolved?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RestrictivePracticeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  type?: Prisma.SortOrder
  isAuthorized?: Prisma.SortOrder
  startTime?: Prisma.SortOrder
  endTime?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  strategies?: Prisma.SortOrder
  staffInvolved?: Prisma.SortOrder
  participantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RestrictivePracticeCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.RestrictivePracticeCreateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput> | Prisma.RestrictivePracticeCreateWithoutParticipantInput[] | Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput | Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.RestrictivePracticeCreateManyParticipantInputEnvelope
  connect?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
}

export type RestrictivePracticeUncheckedCreateNestedManyWithoutParticipantInput = {
  create?: Prisma.XOR<Prisma.RestrictivePracticeCreateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput> | Prisma.RestrictivePracticeCreateWithoutParticipantInput[] | Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput | Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput[]
  createMany?: Prisma.RestrictivePracticeCreateManyParticipantInputEnvelope
  connect?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
}

export type RestrictivePracticeUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.RestrictivePracticeCreateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput> | Prisma.RestrictivePracticeCreateWithoutParticipantInput[] | Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput | Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.RestrictivePracticeUpsertWithWhereUniqueWithoutParticipantInput | Prisma.RestrictivePracticeUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.RestrictivePracticeCreateManyParticipantInputEnvelope
  set?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  disconnect?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  delete?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  connect?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  update?: Prisma.RestrictivePracticeUpdateWithWhereUniqueWithoutParticipantInput | Prisma.RestrictivePracticeUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.RestrictivePracticeUpdateManyWithWhereWithoutParticipantInput | Prisma.RestrictivePracticeUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.RestrictivePracticeScalarWhereInput | Prisma.RestrictivePracticeScalarWhereInput[]
}

export type RestrictivePracticeUncheckedUpdateManyWithoutParticipantNestedInput = {
  create?: Prisma.XOR<Prisma.RestrictivePracticeCreateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput> | Prisma.RestrictivePracticeCreateWithoutParticipantInput[] | Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput[]
  connectOrCreate?: Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput | Prisma.RestrictivePracticeCreateOrConnectWithoutParticipantInput[]
  upsert?: Prisma.RestrictivePracticeUpsertWithWhereUniqueWithoutParticipantInput | Prisma.RestrictivePracticeUpsertWithWhereUniqueWithoutParticipantInput[]
  createMany?: Prisma.RestrictivePracticeCreateManyParticipantInputEnvelope
  set?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  disconnect?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  delete?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  connect?: Prisma.RestrictivePracticeWhereUniqueInput | Prisma.RestrictivePracticeWhereUniqueInput[]
  update?: Prisma.RestrictivePracticeUpdateWithWhereUniqueWithoutParticipantInput | Prisma.RestrictivePracticeUpdateWithWhereUniqueWithoutParticipantInput[]
  updateMany?: Prisma.RestrictivePracticeUpdateManyWithWhereWithoutParticipantInput | Prisma.RestrictivePracticeUpdateManyWithWhereWithoutParticipantInput[]
  deleteMany?: Prisma.RestrictivePracticeScalarWhereInput | Prisma.RestrictivePracticeScalarWhereInput[]
}

export type RestrictivePracticeCreateWithoutParticipantInput = {
  id?: string
  type: string
  isAuthorized: boolean
  startTime: Date | string
  endTime?: Date | string | null
  reason: string
  strategies: string
  staffInvolved: string
  createdAt?: Date | string
}

export type RestrictivePracticeUncheckedCreateWithoutParticipantInput = {
  id?: string
  type: string
  isAuthorized: boolean
  startTime: Date | string
  endTime?: Date | string | null
  reason: string
  strategies: string
  staffInvolved: string
  createdAt?: Date | string
}

export type RestrictivePracticeCreateOrConnectWithoutParticipantInput = {
  where: Prisma.RestrictivePracticeWhereUniqueInput
  create: Prisma.XOR<Prisma.RestrictivePracticeCreateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput>
}

export type RestrictivePracticeCreateManyParticipantInputEnvelope = {
  data: Prisma.RestrictivePracticeCreateManyParticipantInput | Prisma.RestrictivePracticeCreateManyParticipantInput[]
}

export type RestrictivePracticeUpsertWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.RestrictivePracticeWhereUniqueInput
  update: Prisma.XOR<Prisma.RestrictivePracticeUpdateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedUpdateWithoutParticipantInput>
  create: Prisma.XOR<Prisma.RestrictivePracticeCreateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedCreateWithoutParticipantInput>
}

export type RestrictivePracticeUpdateWithWhereUniqueWithoutParticipantInput = {
  where: Prisma.RestrictivePracticeWhereUniqueInput
  data: Prisma.XOR<Prisma.RestrictivePracticeUpdateWithoutParticipantInput, Prisma.RestrictivePracticeUncheckedUpdateWithoutParticipantInput>
}

export type RestrictivePracticeUpdateManyWithWhereWithoutParticipantInput = {
  where: Prisma.RestrictivePracticeScalarWhereInput
  data: Prisma.XOR<Prisma.RestrictivePracticeUpdateManyMutationInput, Prisma.RestrictivePracticeUncheckedUpdateManyWithoutParticipantInput>
}

export type RestrictivePracticeScalarWhereInput = {
  AND?: Prisma.RestrictivePracticeScalarWhereInput | Prisma.RestrictivePracticeScalarWhereInput[]
  OR?: Prisma.RestrictivePracticeScalarWhereInput[]
  NOT?: Prisma.RestrictivePracticeScalarWhereInput | Prisma.RestrictivePracticeScalarWhereInput[]
  id?: Prisma.StringFilter<"RestrictivePractice"> | string
  type?: Prisma.StringFilter<"RestrictivePractice"> | string
  isAuthorized?: Prisma.BoolFilter<"RestrictivePractice"> | boolean
  startTime?: Prisma.DateTimeFilter<"RestrictivePractice"> | Date | string
  endTime?: Prisma.DateTimeNullableFilter<"RestrictivePractice"> | Date | string | null
  reason?: Prisma.StringFilter<"RestrictivePractice"> | string
  strategies?: Prisma.StringFilter<"RestrictivePractice"> | string
  staffInvolved?: Prisma.StringFilter<"RestrictivePractice"> | string
  participantId?: Prisma.StringFilter<"RestrictivePractice"> | string
  createdAt?: Prisma.DateTimeFilter<"RestrictivePractice"> | Date | string
}

export type RestrictivePracticeCreateManyParticipantInput = {
  id?: string
  type: string
  isAuthorized: boolean
  startTime: Date | string
  endTime?: Date | string | null
  reason: string
  strategies: string
  staffInvolved: string
  createdAt?: Date | string
}

export type RestrictivePracticeUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isAuthorized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  strategies?: Prisma.StringFieldUpdateOperationsInput | string
  staffInvolved?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestrictivePracticeUncheckedUpdateWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isAuthorized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  strategies?: Prisma.StringFieldUpdateOperationsInput | string
  staffInvolved?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RestrictivePracticeUncheckedUpdateManyWithoutParticipantInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  isAuthorized?: Prisma.BoolFieldUpdateOperationsInput | boolean
  startTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  strategies?: Prisma.StringFieldUpdateOperationsInput | string
  staffInvolved?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RestrictivePracticeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  isAuthorized?: boolean
  startTime?: boolean
  endTime?: boolean
  reason?: boolean
  strategies?: boolean
  staffInvolved?: boolean
  participantId?: boolean
  createdAt?: boolean
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["restrictivePractice"]>

export type RestrictivePracticeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  isAuthorized?: boolean
  startTime?: boolean
  endTime?: boolean
  reason?: boolean
  strategies?: boolean
  staffInvolved?: boolean
  participantId?: boolean
  createdAt?: boolean
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["restrictivePractice"]>

export type RestrictivePracticeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  type?: boolean
  isAuthorized?: boolean
  startTime?: boolean
  endTime?: boolean
  reason?: boolean
  strategies?: boolean
  staffInvolved?: boolean
  participantId?: boolean
  createdAt?: boolean
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["restrictivePractice"]>

export type RestrictivePracticeSelectScalar = {
  id?: boolean
  type?: boolean
  isAuthorized?: boolean
  startTime?: boolean
  endTime?: boolean
  reason?: boolean
  strategies?: boolean
  staffInvolved?: boolean
  participantId?: boolean
  createdAt?: boolean
}

export type RestrictivePracticeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "type" | "isAuthorized" | "startTime" | "endTime" | "reason" | "strategies" | "staffInvolved" | "participantId" | "createdAt", ExtArgs["result"]["restrictivePractice"]>
export type RestrictivePracticeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}
export type RestrictivePracticeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}
export type RestrictivePracticeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participant?: boolean | Prisma.ParticipantDefaultArgs<ExtArgs>
}

export type $RestrictivePracticePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RestrictivePractice"
  objects: {
    participant: Prisma.$ParticipantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    type: string
    isAuthorized: boolean
    startTime: Date
    endTime: Date | null
    reason: string
    strategies: string
    staffInvolved: string
    participantId: string
    createdAt: Date
  }, ExtArgs["result"]["restrictivePractice"]>
  composites: {}
}

export type RestrictivePracticeGetPayload<S extends boolean | null | undefined | RestrictivePracticeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload, S>

export type RestrictivePracticeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RestrictivePracticeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RestrictivePracticeCountAggregateInputType | true
  }

export interface RestrictivePracticeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RestrictivePractice'], meta: { name: 'RestrictivePractice' } }
  /**
   * Find zero or one RestrictivePractice that matches the filter.
   * @param {RestrictivePracticeFindUniqueArgs} args - Arguments to find a RestrictivePractice
   * @example
   * // Get one RestrictivePractice
   * const restrictivePractice = await prisma.restrictivePractice.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RestrictivePracticeFindUniqueArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RestrictivePractice that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RestrictivePracticeFindUniqueOrThrowArgs} args - Arguments to find a RestrictivePractice
   * @example
   * // Get one RestrictivePractice
   * const restrictivePractice = await prisma.restrictivePractice.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RestrictivePracticeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RestrictivePractice that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestrictivePracticeFindFirstArgs} args - Arguments to find a RestrictivePractice
   * @example
   * // Get one RestrictivePractice
   * const restrictivePractice = await prisma.restrictivePractice.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RestrictivePracticeFindFirstArgs>(args?: Prisma.SelectSubset<T, RestrictivePracticeFindFirstArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RestrictivePractice that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestrictivePracticeFindFirstOrThrowArgs} args - Arguments to find a RestrictivePractice
   * @example
   * // Get one RestrictivePractice
   * const restrictivePractice = await prisma.restrictivePractice.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RestrictivePracticeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RestrictivePracticeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RestrictivePractices that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestrictivePracticeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RestrictivePractices
   * const restrictivePractices = await prisma.restrictivePractice.findMany()
   * 
   * // Get first 10 RestrictivePractices
   * const restrictivePractices = await prisma.restrictivePractice.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const restrictivePracticeWithIdOnly = await prisma.restrictivePractice.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RestrictivePracticeFindManyArgs>(args?: Prisma.SelectSubset<T, RestrictivePracticeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RestrictivePractice.
   * @param {RestrictivePracticeCreateArgs} args - Arguments to create a RestrictivePractice.
   * @example
   * // Create one RestrictivePractice
   * const RestrictivePractice = await prisma.restrictivePractice.create({
   *   data: {
   *     // ... data to create a RestrictivePractice
   *   }
   * })
   * 
   */
  create<T extends RestrictivePracticeCreateArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeCreateArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RestrictivePractices.
   * @param {RestrictivePracticeCreateManyArgs} args - Arguments to create many RestrictivePractices.
   * @example
   * // Create many RestrictivePractices
   * const restrictivePractice = await prisma.restrictivePractice.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RestrictivePracticeCreateManyArgs>(args?: Prisma.SelectSubset<T, RestrictivePracticeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RestrictivePractices and returns the data saved in the database.
   * @param {RestrictivePracticeCreateManyAndReturnArgs} args - Arguments to create many RestrictivePractices.
   * @example
   * // Create many RestrictivePractices
   * const restrictivePractice = await prisma.restrictivePractice.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RestrictivePractices and only return the `id`
   * const restrictivePracticeWithIdOnly = await prisma.restrictivePractice.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RestrictivePracticeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RestrictivePracticeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RestrictivePractice.
   * @param {RestrictivePracticeDeleteArgs} args - Arguments to delete one RestrictivePractice.
   * @example
   * // Delete one RestrictivePractice
   * const RestrictivePractice = await prisma.restrictivePractice.delete({
   *   where: {
   *     // ... filter to delete one RestrictivePractice
   *   }
   * })
   * 
   */
  delete<T extends RestrictivePracticeDeleteArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeDeleteArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RestrictivePractice.
   * @param {RestrictivePracticeUpdateArgs} args - Arguments to update one RestrictivePractice.
   * @example
   * // Update one RestrictivePractice
   * const restrictivePractice = await prisma.restrictivePractice.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RestrictivePracticeUpdateArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeUpdateArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RestrictivePractices.
   * @param {RestrictivePracticeDeleteManyArgs} args - Arguments to filter RestrictivePractices to delete.
   * @example
   * // Delete a few RestrictivePractices
   * const { count } = await prisma.restrictivePractice.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RestrictivePracticeDeleteManyArgs>(args?: Prisma.SelectSubset<T, RestrictivePracticeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RestrictivePractices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestrictivePracticeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RestrictivePractices
   * const restrictivePractice = await prisma.restrictivePractice.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RestrictivePracticeUpdateManyArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RestrictivePractices and returns the data updated in the database.
   * @param {RestrictivePracticeUpdateManyAndReturnArgs} args - Arguments to update many RestrictivePractices.
   * @example
   * // Update many RestrictivePractices
   * const restrictivePractice = await prisma.restrictivePractice.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RestrictivePractices and only return the `id`
   * const restrictivePracticeWithIdOnly = await prisma.restrictivePractice.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RestrictivePracticeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RestrictivePractice.
   * @param {RestrictivePracticeUpsertArgs} args - Arguments to update or create a RestrictivePractice.
   * @example
   * // Update or create a RestrictivePractice
   * const restrictivePractice = await prisma.restrictivePractice.upsert({
   *   create: {
   *     // ... data to create a RestrictivePractice
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RestrictivePractice we want to update
   *   }
   * })
   */
  upsert<T extends RestrictivePracticeUpsertArgs>(args: Prisma.SelectSubset<T, RestrictivePracticeUpsertArgs<ExtArgs>>): Prisma.Prisma__RestrictivePracticeClient<runtime.Types.Result.GetResult<Prisma.$RestrictivePracticePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RestrictivePractices.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestrictivePracticeCountArgs} args - Arguments to filter RestrictivePractices to count.
   * @example
   * // Count the number of RestrictivePractices
   * const count = await prisma.restrictivePractice.count({
   *   where: {
   *     // ... the filter for the RestrictivePractices we want to count
   *   }
   * })
  **/
  count<T extends RestrictivePracticeCountArgs>(
    args?: Prisma.Subset<T, RestrictivePracticeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RestrictivePracticeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RestrictivePractice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestrictivePracticeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RestrictivePracticeAggregateArgs>(args: Prisma.Subset<T, RestrictivePracticeAggregateArgs>): Prisma.PrismaPromise<GetRestrictivePracticeAggregateType<T>>

  /**
   * Group by RestrictivePractice.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RestrictivePracticeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RestrictivePracticeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RestrictivePracticeGroupByArgs['orderBy'] }
      : { orderBy?: RestrictivePracticeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RestrictivePracticeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRestrictivePracticeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RestrictivePractice model
 */
readonly fields: RestrictivePracticeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RestrictivePractice.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RestrictivePracticeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  participant<T extends Prisma.ParticipantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ParticipantDefaultArgs<ExtArgs>>): Prisma.Prisma__ParticipantClient<runtime.Types.Result.GetResult<Prisma.$ParticipantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RestrictivePractice model
 */
export interface RestrictivePracticeFieldRefs {
  readonly id: Prisma.FieldRef<"RestrictivePractice", 'String'>
  readonly type: Prisma.FieldRef<"RestrictivePractice", 'String'>
  readonly isAuthorized: Prisma.FieldRef<"RestrictivePractice", 'Boolean'>
  readonly startTime: Prisma.FieldRef<"RestrictivePractice", 'DateTime'>
  readonly endTime: Prisma.FieldRef<"RestrictivePractice", 'DateTime'>
  readonly reason: Prisma.FieldRef<"RestrictivePractice", 'String'>
  readonly strategies: Prisma.FieldRef<"RestrictivePractice", 'String'>
  readonly staffInvolved: Prisma.FieldRef<"RestrictivePractice", 'String'>
  readonly participantId: Prisma.FieldRef<"RestrictivePractice", 'String'>
  readonly createdAt: Prisma.FieldRef<"RestrictivePractice", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RestrictivePractice findUnique
 */
export type RestrictivePracticeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * Filter, which RestrictivePractice to fetch.
   */
  where: Prisma.RestrictivePracticeWhereUniqueInput
}

/**
 * RestrictivePractice findUniqueOrThrow
 */
export type RestrictivePracticeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * Filter, which RestrictivePractice to fetch.
   */
  where: Prisma.RestrictivePracticeWhereUniqueInput
}

/**
 * RestrictivePractice findFirst
 */
export type RestrictivePracticeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * Filter, which RestrictivePractice to fetch.
   */
  where?: Prisma.RestrictivePracticeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestrictivePractices to fetch.
   */
  orderBy?: Prisma.RestrictivePracticeOrderByWithRelationInput | Prisma.RestrictivePracticeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RestrictivePractices.
   */
  cursor?: Prisma.RestrictivePracticeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestrictivePractices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestrictivePractices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RestrictivePractices.
   */
  distinct?: Prisma.RestrictivePracticeScalarFieldEnum | Prisma.RestrictivePracticeScalarFieldEnum[]
}

/**
 * RestrictivePractice findFirstOrThrow
 */
export type RestrictivePracticeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * Filter, which RestrictivePractice to fetch.
   */
  where?: Prisma.RestrictivePracticeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestrictivePractices to fetch.
   */
  orderBy?: Prisma.RestrictivePracticeOrderByWithRelationInput | Prisma.RestrictivePracticeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RestrictivePractices.
   */
  cursor?: Prisma.RestrictivePracticeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestrictivePractices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestrictivePractices.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RestrictivePractices.
   */
  distinct?: Prisma.RestrictivePracticeScalarFieldEnum | Prisma.RestrictivePracticeScalarFieldEnum[]
}

/**
 * RestrictivePractice findMany
 */
export type RestrictivePracticeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * Filter, which RestrictivePractices to fetch.
   */
  where?: Prisma.RestrictivePracticeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RestrictivePractices to fetch.
   */
  orderBy?: Prisma.RestrictivePracticeOrderByWithRelationInput | Prisma.RestrictivePracticeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RestrictivePractices.
   */
  cursor?: Prisma.RestrictivePracticeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RestrictivePractices from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RestrictivePractices.
   */
  skip?: number
  distinct?: Prisma.RestrictivePracticeScalarFieldEnum | Prisma.RestrictivePracticeScalarFieldEnum[]
}

/**
 * RestrictivePractice create
 */
export type RestrictivePracticeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * The data needed to create a RestrictivePractice.
   */
  data: Prisma.XOR<Prisma.RestrictivePracticeCreateInput, Prisma.RestrictivePracticeUncheckedCreateInput>
}

/**
 * RestrictivePractice createMany
 */
export type RestrictivePracticeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RestrictivePractices.
   */
  data: Prisma.RestrictivePracticeCreateManyInput | Prisma.RestrictivePracticeCreateManyInput[]
}

/**
 * RestrictivePractice createManyAndReturn
 */
export type RestrictivePracticeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * The data used to create many RestrictivePractices.
   */
  data: Prisma.RestrictivePracticeCreateManyInput | Prisma.RestrictivePracticeCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RestrictivePractice update
 */
export type RestrictivePracticeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * The data needed to update a RestrictivePractice.
   */
  data: Prisma.XOR<Prisma.RestrictivePracticeUpdateInput, Prisma.RestrictivePracticeUncheckedUpdateInput>
  /**
   * Choose, which RestrictivePractice to update.
   */
  where: Prisma.RestrictivePracticeWhereUniqueInput
}

/**
 * RestrictivePractice updateMany
 */
export type RestrictivePracticeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RestrictivePractices.
   */
  data: Prisma.XOR<Prisma.RestrictivePracticeUpdateManyMutationInput, Prisma.RestrictivePracticeUncheckedUpdateManyInput>
  /**
   * Filter which RestrictivePractices to update
   */
  where?: Prisma.RestrictivePracticeWhereInput
  /**
   * Limit how many RestrictivePractices to update.
   */
  limit?: number
}

/**
 * RestrictivePractice updateManyAndReturn
 */
export type RestrictivePracticeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * The data used to update RestrictivePractices.
   */
  data: Prisma.XOR<Prisma.RestrictivePracticeUpdateManyMutationInput, Prisma.RestrictivePracticeUncheckedUpdateManyInput>
  /**
   * Filter which RestrictivePractices to update
   */
  where?: Prisma.RestrictivePracticeWhereInput
  /**
   * Limit how many RestrictivePractices to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RestrictivePractice upsert
 */
export type RestrictivePracticeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * The filter to search for the RestrictivePractice to update in case it exists.
   */
  where: Prisma.RestrictivePracticeWhereUniqueInput
  /**
   * In case the RestrictivePractice found by the `where` argument doesn't exist, create a new RestrictivePractice with this data.
   */
  create: Prisma.XOR<Prisma.RestrictivePracticeCreateInput, Prisma.RestrictivePracticeUncheckedCreateInput>
  /**
   * In case the RestrictivePractice was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RestrictivePracticeUpdateInput, Prisma.RestrictivePracticeUncheckedUpdateInput>
}

/**
 * RestrictivePractice delete
 */
export type RestrictivePracticeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
  /**
   * Filter which RestrictivePractice to delete.
   */
  where: Prisma.RestrictivePracticeWhereUniqueInput
}

/**
 * RestrictivePractice deleteMany
 */
export type RestrictivePracticeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RestrictivePractices to delete
   */
  where?: Prisma.RestrictivePracticeWhereInput
  /**
   * Limit how many RestrictivePractices to delete.
   */
  limit?: number
}

/**
 * RestrictivePractice without action
 */
export type RestrictivePracticeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RestrictivePractice
   */
  select?: Prisma.RestrictivePracticeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RestrictivePractice
   */
  omit?: Prisma.RestrictivePracticeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RestrictivePracticeInclude<ExtArgs> | null
}
